# Generated by Django 2.1.2 on 2019-06-18 11:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterBoard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_started', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('type_of_plan', models.CharField(blank=True, max_length=150, null=True)),
                ('type_of_crm', models.CharField(blank=True, max_length=150, null=True)),
                ('type_of_voip', models.CharField(blank=True, max_length=150, null=True)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('url_buyer', models.URLField(blank=True, null=True)),
                ('url_seller', models.URLField(blank=True, null=True)),
                ('url_property_management', models.URLField(blank=True, null=True)),
                ('voicemail', models.CharField(blank=True, max_length=150, null=True)),
                ('general_calls', models.CharField(blank=True, max_length=150, null=True)),
                ('client_name', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.Clients')),
            ],
            options={
                'verbose_name': 'CallMe Master Board',
                'verbose_name_plural': 'CallMe Master Boards',
                'ordering': ['-date_started'],
            },
        ),
    ]
