# Generated by Django 2.1.2 on 2019-06-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callmemasterboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterboard',
            name='client_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
