# Generated by Django 2.1.2 on 2019-06-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callmemasterboard', '0002_auto_20190622_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterboard',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
