# Generated by Django 2.1.2 on 2019-07-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callmemasterboard', '0005_masterboard_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterboard',
            name='crm_login',
            field=models.TextField(blank=True, null=True, verbose_name='CRM System - Log In Information'),
        ),
        migrations.AddField(
            model_name='masterboard',
            name='phone_login',
            field=models.TextField(blank=True, null=True, verbose_name='Phone System - Log In Information'),
        ),
    ]
