# Generated by Django 2.1.2 on 2019-07-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callmemasterboard', '0006_auto_20190703_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterboard',
            name='call_forwarding_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterboard',
            name='email_form_forwarding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
