# Generated by Django 2.1.2 on 2019-07-17 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callmemasterboard', '0007_auto_20190709_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterboard',
            name='company_name',
        ),
    ]
