# Generated by Django 2.1.2 on 2019-07-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callmemasterboard', '0008_remove_masterboard_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterboard',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Ready to Start', 'Ready to Start'), ('For Follow-up', 'For Follow-up')], max_length=100, null=True),
        ),
    ]
