# Generated by Django 2.1.2 on 2019-08-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callmemasterboard', '0011_textfield_for_gs_andclient_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterboard',
            name='monthly_plan_cost',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
