# Generated by Django 2.1.2 on 2019-03-27 09:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fillables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualAssistant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'List of VA',
                'verbose_name_plural': 'List of VAs',
            },
        ),
    ]
