# Generated by Django 2.1.2 on 2019-07-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='life_insurance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='maxicare_health_insurance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='monthly_bonus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='others',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='retirement_plan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='total_compensation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='company_category',
            field=models.CharField(blank=True, choices=[('landmaster.us', 'landmaster.us'), ('gpgcorporation.com', 'gpgcorporation.com'), ('callme.com.ph', 'callme.com.ph'), ('virtualExpressServices.com', 'virtualExpressServices.com'), ('creatif-designs.com', 'creatif-designs.com'), ('vacantpropertiesglobal.com', 'vacantpropertiesglobal.com')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='position',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('Chief Finance Officer', 'Chief Finance Officer'), ('Senior Operation Manager', 'Senior Operation Manager'), ('Operation Manager', 'Operation Manager'), ('Admin Manager', 'Admin Manager'), ('Senior Operations Manager', 'Senior Operations Manager'), ('Project Manager', 'Project Manager'), ('Team Lead', 'Team Lead'), ('General Administrative Support', 'General Administrative Support'), ('Executive Assistant to CEO', 'Executive Assistant to CEO'), ('Human Resource Specialist', 'Human Resource Specialist'), ('Recruitment Specialist', 'Recruitment Specialist'), ('IT Manager', 'IT Manager'), ('IT Support', 'IT Support'), ('Customer Support', 'Customer Support')], max_length=150, null=True),
        ),
    ]
