# Generated by Django 2.1.2 on 2018-12-21 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181218_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'List of Staff', 'verbose_name_plural': 'List of Staff'},
        ),
    ]
