# Generated by Django 2.1.2 on 2018-10-25 17:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181026_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='emergency_contact_number',
            field=models.CharField(default=datetime.datetime(2018, 10, 25, 17, 24, 39, 92703, tzinfo=utc), max_length=250),
            preserve_default=False,
        ),
    ]
