# Generated by Django 2.1.2 on 2019-07-19 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_removed_s_from_job_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelofcommunications',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channels', to='users.Clients'),
        ),
        migrations.AlterField(
            model_name='email',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emails', to='users.Clients'),
        ),
        migrations.AlterField(
            model_name='paypalemail',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paypals', to='users.Clients'),
        ),
        migrations.AlterField(
            model_name='trainingurl',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trainingurls', to='users.Clients'),
        ),
        migrations.AlterField(
            model_name='typeoftaskrequest',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='typeoftasks', to='users.Clients'),
        ),
        migrations.AlterField(
            model_name='websiteurl',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='websiteurls', to='users.Clients'),
        ),
    ]
