# Generated by Django 2.1.2 on 2018-12-21 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181221_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'List of Staff'},
        ),
    ]
