# Generated by Django 2.1.2 on 2018-11-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_emergency_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='My Name', max_length=250),
        ),
    ]
