# Generated by Django 2.1.2 on 2019-04-09 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181221_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='SSS_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='TIN_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='emergency_contact_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='father_full_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mother_full_maiden_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pag_ibig_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='philhealth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='position',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='relationship_to_the_emergency_contact_person',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='residential_address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
    ]
