# Generated by Django 2.1.2 on 2019-04-09 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190409_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'List of Client',
                'verbose_name_plural': 'List of Clients',
            },
        ),
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='My Name', max_length=250)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('SSS_number', models.CharField(blank=True, max_length=250, null=True)),
                ('TIN_number', models.CharField(blank=True, max_length=250, null=True)),
                ('pag_ibig_number', models.CharField(blank=True, max_length=250, null=True)),
                ('philhealth', models.CharField(blank=True, max_length=250, null=True)),
                ('position', models.CharField(blank=True, max_length=250, null=True)),
                ('id_number', models.CharField(blank=True, max_length=250, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=150, null=True)),
                ('mother_full_maiden_name', models.CharField(blank=True, max_length=250, null=True)),
                ('father_full_name', models.CharField(blank=True, max_length=250, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=250, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=250, null=True)),
                ('relationship_to_the_emergency_contact_person', models.CharField(blank=True, max_length=200, null=True)),
                ('residential_address', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('REGULAR', 'Regular'), ('PROBATIONARY', 'Probationary'), ('INACTIVE', 'Inactive')], max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'List of Staff',
                'verbose_name_plural': 'List of Staffs',
                'ordering': ['full_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['notes'], 'verbose_name': 'List of Username', 'verbose_name_plural': 'List of Usernames'},
        ),
        migrations.AddField(
            model_name='staffs',
            name='user_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='staffs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clients',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
