# Generated by Django 2.1.2 on 2019-07-20 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_added_default_for_compensation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AddField(
            model_name='clients',
            name='channel_of_communications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channels', to='users.ChannelOfCommunications'),
        ),
        migrations.AddField(
            model_name='clients',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emails', to='users.Email'),
        ),
        migrations.AddField(
            model_name='clients',
            name='paypay_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paypals', to='users.PaypalEmail'),
        ),
        migrations.AddField(
            model_name='clients',
            name='training_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trainingnurls', to='users.TrainingUrl'),
        ),
        migrations.AddField(
            model_name='clients',
            name='type_of_task_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='users.TypeOfTaskRequest'),
        ),
        migrations.AddField(
            model_name='clients',
            name='website_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='websites', to='users.WebsiteUrl'),
        ),
        migrations.AlterField(
            model_name='channelofcommunications',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='paypalemail',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='trainingurl',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='typeoftaskrequest',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='websiteurl',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
