# Generated by Django 2.1.2 on 2019-04-09 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190409_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffs',
            old_name='user_name',
            new_name='username',
        ),
    ]
