# Generated by Django 2.1.2 on 2019-07-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190720_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='email',
        ),
        migrations.AddField(
            model_name='clients',
            name='email',
            field=models.ManyToManyField(blank=True, null=True, related_name='emails', to='users.Email'),
        ),
    ]
