# Generated by Django 2.1.2 on 2019-07-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190720_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='channel_of_communications',
        ),
        migrations.AddField(
            model_name='clients',
            name='channel_of_communications',
            field=models.ManyToManyField(blank=True, null=True, related_name='channels', to='users.ChannelOfCommunications'),
        ),
        migrations.RemoveField(
            model_name='clients',
            name='paypay_email',
        ),
        migrations.AddField(
            model_name='clients',
            name='paypay_email',
            field=models.ManyToManyField(blank=True, null=True, related_name='paypals', to='users.PaypalEmail'),
        ),
        migrations.RemoveField(
            model_name='clients',
            name='training_url',
        ),
        migrations.AddField(
            model_name='clients',
            name='training_url',
            field=models.ManyToManyField(blank=True, null=True, related_name='trainingnurls', to='users.TrainingUrl'),
        ),
        migrations.RemoveField(
            model_name='clients',
            name='type_of_task_request',
        ),
        migrations.AddField(
            model_name='clients',
            name='type_of_task_request',
            field=models.ManyToManyField(blank=True, null=True, related_name='tasks', to='users.TypeOfTaskRequest'),
        ),
        migrations.RemoveField(
            model_name='clients',
            name='website_url',
        ),
        migrations.AddField(
            model_name='clients',
            name='website_url',
            field=models.ManyToManyField(blank=True, null=True, related_name='websites', to='users.WebsiteUrl'),
        ),
    ]
