# Generated by Django 2.1.2 on 2019-07-20 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190720_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='paypay_email',
            new_name='paypal_email',
        ),
    ]
