# Generated by Django 2.1.2 on 2019-07-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190720_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='channel_of_communications',
            field=models.ManyToManyField(blank=True, related_name='channels', to='users.ChannelOfCommunications'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.ManyToManyField(blank=True, related_name='emails', to='users.Email'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='paypal_email',
            field=models.ManyToManyField(blank=True, related_name='paypals', to='users.PaypalEmail'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='training_url',
            field=models.ManyToManyField(blank=True, related_name='trainingnurls', to='users.TrainingUrl'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='type_of_task_request',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='users.TypeOfTaskRequest'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='website_url',
            field=models.ManyToManyField(blank=True, related_name='websites', to='users.WebsiteUrl'),
        ),
    ]
