# Generated by Django 2.1.2 on 2019-08-01 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_removed_null_on_many2many'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='assigned_pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_managers', to='users.Staffs', verbose_name='Assigned PM'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='assigned_va',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='virtual_assistants', to='users.Staffs', verbose_name='Assigned VA'),
        ),
    ]
