# Generated by Django 2.1.2 on 2019-04-20 07:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190416_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaypalEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_email_address', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='clients',
            name='client_control_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='date_signed_up',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websiteurl',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Clients'),
        ),
        migrations.AddField(
            model_name='paypalemail',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Clients'),
        ),
        migrations.AddField(
            model_name='email',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Clients'),
        ),
    ]
