# Generated by Django 2.1.2 on 2019-05-04 04:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fillables', '0002_added_va'),
        ('users', '0013_auto_20190420_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfiling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_of_client', models.CharField(max_length=150)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='clients',
            name='assigned_pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.ProjectManager'),
        ),
        migrations.AddField(
            model_name='clients',
            name='assigned_va',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.VirtualAssistant'),
        ),
        migrations.AddField(
            model_name='clients',
            name='internal_folder_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='task_enroute',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='type_of_task',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='bank_account_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffs',
            name='bank_account_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffs',
            name='bank_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffs',
            name='bank_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clients',
            name='date_signed_up',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='trainingurl',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Clients'),
        ),
    ]
