# Generated by Django 2.1.2 on 2019-05-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190504_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='bank_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
