# Generated by Django 2.1.2 on 2019-05-30 03:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20190505_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='actual_date_hired',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='base_pay',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='date_hired_in_contract',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='employee_share_ec_sss',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Employee share EC(SSS)', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='employee_share_pag_ibig',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Employee share(PAG-IBIG)', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='employee_share_philhealth',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Employee share(PHILHEALTH)', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='employee_share_sss',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Employee share(SSS)', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='employer_share_ec_sss',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Employer share EC(SSS)', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='employer_share_pag_ibig',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Employer share(PAG-IBIG)', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='employer_share_philhealth',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Employer share(PHILHEALTH)', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='employer_share_sss',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Employer share(SSS)', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='middle_name',
            field=models.CharField(blank=True, default='middle name', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='total_employee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='staffs',
            name='total_employer',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='philhealth',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Philhealth Number'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='position',
            field=models.CharField(blank=True, choices=[('Senior Operations Managers', 'Senior Operations Managers'), ('Project Managers', 'Project Managers'), ('Team Leads', 'Team Leads'), ('General Administrative Support', 'General Administrative Support'), ('Executive Assistant', 'Executive Assistant'), ('Human Resource Specialists', 'Human Resource Specialists')], max_length=150, null=True),
        ),
    ]
