# Generated by Django 2.1.2 on 2019-05-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_added_computations_for_shares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='employee_share_ec_sss',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Employee share EC(SSS)'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='employee_share_pag_ibig',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Employee share(PAG-IBIG)'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='employee_share_philhealth',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Employee share(PHILHEALTH)'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='employee_share_sss',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Employee share(SSS)'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='employer_share_ec_sss',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Employer share EC(SSS)'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='employer_share_pag_ibig',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Employer share(PAG-IBIG)'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='employer_share_philhealth',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Employer share(PHILHEALTH)'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='employer_share_sss',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Employer share(SSS)'),
        ),
    ]
