# Generated by Django 2.1.2 on 2019-06-04 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_changed_help_text_to_verbose_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfTaskRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='referral',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='clients',
            name='referred_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='assigned_pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.ProjectManager', verbose_name='Assigned PM'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='assigned_va',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.VirtualAssistant', verbose_name='Assigned VA'),
        ),
    ]
