# Generated by Django 2.1.2 on 2019-06-04 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20190604_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeoftaskrequest',
            name='name_of_task',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='typeoftaskrequest',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Clients'),
        ),
    ]
