# Generated by Django 2.1.2 on 2019-06-04 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_clients_lead_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelOfCommunications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_channel', models.CharField(blank=True, max_length=150, null=True)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Clients')),
            ],
        ),
        migrations.CreateModel(
            name='NotesAfterTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Clients')),
            ],
        ),
    ]
