# Generated by Django 2.1.2 on 2019-06-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20190604_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='employee_tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='overall_total_share',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='total_share_ec_sss',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='total_share_pag_ibig',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='total_share_philhealth',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='total_share_sss',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
    ]
