# Generated by Django 2.1.2 on 2019-06-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20190604_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
