# Generated by Django 2.1.2 on 2019-06-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_staffs_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='internal_folder_link',
            new_name='internal_folder_link_1',
        ),
        migrations.AddField(
            model_name='clients',
            name='internal_folder_link_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='internal_folder_link_3',
            field=models.URLField(blank=True, null=True),
        ),
    ]
