# Generated by Django 2.1.2 on 2019-06-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20190604_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='company_category',
            field=models.CharField(blank=True, choices=[('landmaster.us', 'landmaster.us'), ('gpgcorporations.com', 'gpgcorporations.com'), ('callme.com.ph', 'callme.com.ph'), ('virtualExpressServices.com', 'virtualExpressServices.com'), ('creatif-designs.com', 'creatif-designs.com'), ('vacantpropertiesglobal.com', 'vacantpropertiesglobal.com')], max_length=150, null=True),
        ),
    ]
