# Generated by Django 2.1.2 on 2019-06-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_clients_company_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Active', 'Active'), ('Inactive within 30 days', 'Inactive within 30 days'), ('Inactive within 90 days', 'Inactive within 90 days'), ('Inactive within 120 days', 'Inactive within 120 days'), ('Sign out', 'Sign out'), ('Terminated', 'Terminated'), ('Others', 'Others')], default='New', max_length=150, null=True),
        ),
    ]
