# Generated by Django 2.1.2 on 2019-06-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_clients_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='full_name',
            field=models.CharField(default='My Name', max_length=500),
        ),
    ]
