# Generated by Django 2.1.2 on 2019-06-11 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_adjusted_the_max_length_full_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotesAfterTraining',
            new_name='Notes',
        ),
    ]
