# Generated by Django 2.1.2 on 2019-06-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_changed_name_of_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofiling',
            name='category',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Average', 'Average'), ('Low', 'Low')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='clientprofiling',
            name='current_job_position',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='clientprofiling',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofiling',
            name='feedback_in_operation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofiling',
            name='feedback_in_quality',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofiling',
            name='influence',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='clientprofiling',
            name='line',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='clientprofiling',
            name='notes_on_disputes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofiling',
            name='others',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='clientprofiling',
            name='qualified_for_testimony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientprofiling',
            name='skype_account',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='clientprofiling',
            name='testimony_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofiling',
            name='viber',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='clientprofiling',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
