# Generated by Django 2.1.2 on 2019-06-27 13:50

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandAcademyInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_completed', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_paid', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('pivot_table', models.URLField(blank=True, null=True)),
                ('project_status', models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In Progress', 'In Progress')], max_length=150, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=150, null=True)),
                ('invoice', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Land Academy Inventory Record',
                'verbose_name_plural': 'Land Academy Inventory Records',
                'ordering': ['-date_completed'],
            },
        ),
    ]
