# Generated by Django 2.1.2 on 2019-06-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landacademy', '0002_o20smartpricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='o20smartpricing',
            name='quality_check_status',
            field=models.CharField(blank=True, choices=[('Complete', 'Complete'), ('Complete Incorrect Data Input', 'Complete Incorrect Data Input'), ('Others', 'Others')], max_length=50, null=True),
        ),
    ]
