# Generated by Django 2.1.2 on 2019-06-28 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landacademy', '0003_auto_20190627_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='o20smartpricing',
            old_name='encoder',
            new_name='order_name',
        ),
        migrations.RemoveField(
            model_name='o20smartpricing',
            name='notes',
        ),
        migrations.AddField(
            model_name='o20smartpricing',
            name='date_requested',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='o20smartpricing',
            name='date_research',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='o20smartpricing',
            name='notes_from_qa',
            field=models.TextField(blank=True, null=True, verbose_name='Notes From the QA Specialist'),
        ),
        migrations.AddField(
            model_name='o20smartpricing',
            name='notes_from_researcher',
            field=models.TextField(blank=True, null=True, verbose_name='Notes From the Researcher'),
        ),
        migrations.AddField(
            model_name='o20smartpricing',
            name='requestor_full_name',
            field=models.CharField(default='Jack Butala', max_length=150),
        ),
        migrations.AddField(
            model_name='o20smartpricing',
            name='researcher_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
