# Generated by Django 2.1.2 on 2019-06-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landacademy', '0005_auto_20190628_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landacademyinventory',
            name='total_items_requested',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
