# Generated by Django 2.1.2 on 2019-06-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landacademy', '0006_auto_20190628_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landacademyinventory',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=150, null=True),
        ),
    ]
