# Generated by Django 2.1.2 on 2019-06-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landacademy', '0007_auto_20190628_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landacademyinventory',
            name='total_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Charge + Total PP Fee', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='landacademyinventory',
            name='total_items_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Items Requested x $.10', max_digits=7, null=True, verbose_name='Total Charge'),
        ),
        migrations.AlterField(
            model_name='landacademyinventory',
            name='total_pp_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Charge *.05', max_digits=7, null=True, verbose_name='Total PP Fee'),
        ),
    ]
