# Generated by Django 2.1.2 on 2019-07-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landacademy', '0008_auto_20190628_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landacademyinventory',
            name='complete_order',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Complete Order - URL Link'),
        ),
    ]
