# Generated by Django 2.1.2 on 2019-08-03 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landacademy', '0009_auto_20190717_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='o20smartpricing',
            name='quality_specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='QA', to='users.Staffs'),
        ),
        migrations.AlterField(
            model_name='o20smartpricing',
            name='researcher_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='researcher', to='users.Staffs'),
        ),
    ]
