# Generated by Django 2.1.2 on 2019-09-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landacademy', '0010_used_staffs_for_QA_and_researcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landacademyinventory',
            name='total_items_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Items Requested x $.06', max_digits=7, null=True, verbose_name='Total Charge'),
        ),
    ]
