# Generated by Django 2.1.2 on 2019-09-27 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_clients_notes'),
        ('landacademy', '0011_changed_the_percentage_for_total_items_charge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landacademyinventory',
            options={'ordering': ['-date_completed'], 'verbose_name': 'Smart Pricing Inventory', 'verbose_name_plural': 'Smart Pricing Inventories'},
        ),
        migrations.AlterModelOptions(
            name='o20smartpricing',
            options={'ordering': ['-date_completed'], 'verbose_name': 'Smart Pricing Job Request', 'verbose_name_plural': 'Smart Pricing Job Requests'},
        ),
        migrations.RenameField(
            model_name='o20smartpricing',
            old_name='date_encoded',
            new_name='date_completed',
        ),
        migrations.RenameField(
            model_name='o20smartpricing',
            old_name='order_name',
            new_name='job_order',
        ),
        migrations.RemoveField(
            model_name='o20smartpricing',
            name='date_requested',
        ),
        migrations.RemoveField(
            model_name='o20smartpricing',
            name='date_research',
        ),
        migrations.RemoveField(
            model_name='o20smartpricing',
            name='notes_from_qa',
        ),
        migrations.RemoveField(
            model_name='o20smartpricing',
            name='notes_from_researcher',
        ),
        migrations.RemoveField(
            model_name='o20smartpricing',
            name='quality_check_status',
        ),
        migrations.RemoveField(
            model_name='o20smartpricing',
            name='quality_specialist',
        ),
        migrations.RemoveField(
            model_name='o20smartpricing',
            name='requestor_full_name',
        ),
        migrations.RemoveField(
            model_name='o20smartpricing',
            name='researcher_name',
        ),
        migrations.AddField(
            model_name='o20smartpricing',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Clients'),
        ),
        migrations.AddField(
            model_name='o20smartpricing',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='o20smartpricing',
            name='virtual_assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='va', to='users.Staffs'),
        ),
    ]
