# Generated by Django 2.1.2 on 2019-09-27 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_clients_notes'),
        ('landacademy', '0012_auto_20190927_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landacademyinventory',
            name='client_la_requestor',
        ),
        migrations.AddField(
            model_name='landacademyinventory',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Clients', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='landacademyinventory',
            name='invoice',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Invoice Number'),
        ),
    ]
