# Generated by Django 2.1.2 on 2018-12-24 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fillables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_sign_up', models.DateField(blank=True, null=True)),
                ('client_company_name', models.CharField(blank=True, max_length=250, null=True)),
                ('agreed_hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('client_code', models.CharField(blank=True, max_length=150, null=True)),
                ('client_phone_number', models.CharField(blank=True, max_length=150, null=True)),
                ('client_email', models.EmailField(blank=True, max_length=250, null=True)),
                ('referred_by', models.CharField(blank=True, max_length=250, null=True)),
                ('clients_count_number', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('VA_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('clients_project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.ProjectManager')),
                ('company_category_under', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.InternalCompanyName')),
                ('company_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.CompanyName', verbose_name="Client Owner's Name")),
                ('lead_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.LeadSource')),
                ('senior_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.SeniorManager')),
                ('type_of_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.TypeOfTask')),
            ],
            options={
                'verbose_name': 'List of Client',
                'verbose_name_plural': 'List of Clients',
                'ordering': ['-date_sign_up'],
            },
        ),
    ]
