# Generated by Django 2.1.2 on 2018-12-18 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Company name',
                'verbose_name_plural': 'Company names',
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lead_source', models.CharField(blank=True, max_length=250, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lead Source',
                'verbose_name_plural': 'Lead Sources',
            },
        ),
        migrations.RenameModel(
            old_name='CompanyCategory',
            new_name='InternalCompanyName',
        ),
        migrations.DeleteModel(
            name='ClientName',
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-date_sign_up'], 'verbose_name': 'List of Client', 'verbose_name_plural': 'List of Clients'},
        ),
        migrations.AlterModelOptions(
            name='internalcompanyname',
            options={'verbose_name_plural': 'Internal Company Names'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='clients_company_name',
        ),
        migrations.AddField(
            model_name='client',
            name='VA_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='client_company_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='clients_project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.ProjectManager'),
        ),
        migrations.AddField(
            model_name='client',
            name='company_category_under',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.InternalCompanyName'),
        ),
        migrations.AddField(
            model_name='client',
            name='senior_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.SeniorManager'),
        ),
        migrations.AddField(
            model_name='client',
            name='type_of_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.TypeOfTask'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_phone_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='clients_count_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='typeoftask',
            name='task_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CompanyName', to='client.CompanyName', verbose_name="Client Owner's Name"),
        ),
        migrations.AddField(
            model_name='client',
            name='lead_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.LeadSource'),
        ),
    ]
