# Generated by Django 2.1.2 on 2018-10-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company_category',
            new_name='ClientName',
        ),
        migrations.RenameModel(
            old_name='Client_name',
            new_name='CompanyCategory',
        ),
        migrations.RenameModel(
            old_name='Project_Manager',
            new_name='ProjectManager',
        ),
        migrations.RenameModel(
            old_name='Type_of_task',
            new_name='TypeOfTask',
        ),
        migrations.RenameField(
            model_name='clientname',
            old_name='company_name',
            new_name='client_name',
        ),
        migrations.RenameField(
            model_name='companycategory',
            old_name='client_name',
            new_name='company_name',
        ),
    ]
