# Generated by Django 2.1.2 on 2018-11-25 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='VA_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ClientName', to='client.ClientName'),
        ),
        migrations.AddField(
            model_name='client',
            name='clients_project_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.ProjectManager'),
        ),
        migrations.AddField(
            model_name='client',
            name='company_category_under',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.CompanyCategory'),
        ),
        migrations.AddField(
            model_name='client',
            name='lead_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.Lead'),
        ),
        migrations.AddField(
            model_name='client',
            name='senior_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.SeniorManager'),
        ),
        migrations.AddField(
            model_name='client',
            name='type_of_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.TypeOfTask'),
        ),
    ]
