# Generated by Django 2.1.2 on 2019-06-11 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('users', '0001_initial'),
        ('fillables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='VA_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Staffs'),
        ),
        migrations.AddField(
            model_name='client',
            name='clients_project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.ProjectManager'),
        ),
        migrations.AddField(
            model_name='client',
            name='company_category_under',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.InternalCompanyName'),
        ),
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.CompanyName', verbose_name="Client Owner's Name"),
        ),
        migrations.AddField(
            model_name='client',
            name='lead_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.LeadSource'),
        ),
        migrations.AddField(
            model_name='client',
            name='senior_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.SeniorManager'),
        ),
        migrations.AddField(
            model_name='client',
            name='type_of_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.TypeOfTask'),
        ),
    ]
