# Generated by Django 2.1.2 on 2019-09-20 05:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_clients_notes'),
        ('client', '0002_auto_20190611_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLeadSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_lead_received', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('lead_source', models.CharField(blank=True, choices=[('Craiglists', 'Craiglists'), ('Facebook', 'Facebook'), ('KSL.Com', 'KSL.Com'), ('Website', 'Website'), ('LandPin', 'LandPin'), ('Zillow', 'Zillow'), ('LandandFarm', 'LandandFarm'), ('Lands of America', 'Lands of America'), ('Facebook', 'Facebook'), ('Facebook Marketplace', 'Facebook Marketplace'), ('Property Control Center', 'Property Control Center'), ('Neighbor Letters', 'Neighbor Letters'), ('Mailchimp', 'Mailchimp'), ('Landstay', 'Landstay'), ('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('Others', 'Others')], max_length=150, null=True)),
                ('full_name_of_lead', models.CharField(blank=True, max_length=150, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('type_of_lead', models.CharField(blank=True, max_length=150, null=True)),
                ('lead_profile_url', models.CharField(blank=True, max_length=150, null=True)),
                ('lead_profile_under', models.CharField(blank=True, max_length=150, null=True)),
                ('lead_status', models.CharField(blank=True, choices=[('Dead Lead', 'Dead Lead'), ('Hot Leads', 'Hot Leads'), ('Requires Follow up', 'Requires Follow up'), ('Interested', 'Interested'), ('Not Interested', 'Not Interested'), ('Inquires Only', 'Inquires Only'), ('Others', 'Others'), ('Closed Sale', 'Closed Sale')], max_length=150, null=True)),
                ('notes_from_client', models.TextField(blank=True, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Clients')),
                ('virtual_assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Staffs')),
            ],
            options={
                'verbose_name': 'Clients Lead Source Inventory',
                'verbose_name_plural': 'Clients Lead Source Inventories',
                'ordering': ['-date_lead_received'],
            },
        ),
    ]
