# Generated by Django 2.1.2 on 2018-10-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20181029_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('NEW', 'New')], default='New', max_length=250),
        ),
    ]
