# Generated by Django 2.1.2 on 2018-11-26 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20181125_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Add Client job'},
        ),
    ]
