# Generated by Django 2.1.2 on 2018-12-21 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20181219_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clients_project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.ProjectManager'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_category_under',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.InternalCompanyName'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.CompanyName', verbose_name="Client Owner's Name"),
        ),
        migrations.AlterField(
            model_name='client',
            name='lead_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.LeadSource'),
        ),
        migrations.AlterField(
            model_name='client',
            name='senior_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.SeniorManager'),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_of_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.TypeOfTask'),
        ),
        migrations.DeleteModel(
            name='CompanyName',
        ),
        migrations.DeleteModel(
            name='InternalCompanyName',
        ),
        migrations.DeleteModel(
            name='LeadSource',
        ),
        migrations.DeleteModel(
            name='ProjectManager',
        ),
        migrations.DeleteModel(
            name='SeniorManager',
        ),
        migrations.DeleteModel(
            name='TypeOfTask',
        ),
    ]
