# Generated by Django 2.1.2 on 2019-09-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_clientleadsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientleadsource',
            name='others',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
