# Generated by Django 2.1.2 on 2018-11-01 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientname',
            old_name='client_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='client',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ClientName', to='client.ClientName'),
        ),
    ]
