# Generated by Django 2.1.2 on 2018-11-03 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20181102_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='agreed_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_category_under',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.CompanyCategory'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_sign_up',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='lead_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.Lead'),
        ),
        migrations.AlterField(
            model_name='client',
            name='referred_by',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='senior_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.SeniorManager'),
        ),
    ]
