# Generated by Django 2.1.2 on 2018-11-26 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20181126_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companycategory',
            options={'verbose_name_plural': 'Company Categories'},
        ),
    ]
