# Generated by Django 2.1.2 on 2019-09-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_clientleadsource_others'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientleadsource',
            name='others',
            field=models.CharField(blank=True, help_text="If Lead source is 'Others' please fill this.", max_length=150, null=True),
        ),
    ]
