# Generated by Django 2.1.2 on 2018-12-05 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20181126_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': (('can_view', 'Can view client'), ('can_add', 'Can add client'), ('can_change', 'Can change client'), ('can_delete', 'Can delete client'))},
        ),
    ]
