# Generated by Django 2.1.2 on 2018-11-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20181103_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=100),
        ),
        migrations.DeleteModel(
            name='StatusChoice',
        ),
    ]
