# Generated by Django 2.1.2 on 2019-06-11 14:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_name', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('educational_attainment', models.TextField(max_length=250)),
                ('work_experience', models.CharField(blank=True, max_length=150, null=True)),
                ('training_workshop_seminar_attended', models.TextField(blank=True, null=True)),
                ('reference_contact', models.CharField(blank=True, max_length=150, null=True)),
                ('communication_assessment', models.CharField(blank=True, max_length=150, null=True)),
                ('technical_skills_assessment', models.CharField(blank=True, max_length=150, null=True)),
                ('other_skills', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, max_length=1000, null=True, upload_to='resume/')),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='reference',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recruitment.Resume'),
        ),
    ]
