# Generated by Django 2.1.2 on 2019-05-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_reference_reference_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='attachment',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='resume/'),
        ),
    ]
