# Generated by Django 2.1.2 on 2019-03-25 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_added_all_seller_forms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solidworkproperties',
            old_name='other_owenrs',
            new_name='other_owners',
        ),
    ]
