# Generated by Django 2.1.2 on 2019-06-18 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affordablelandinvestment',
            name='customer_care_specialist',
        ),
        migrations.DeleteModel(
            name='AffordableLandSpiels',
        ),
        migrations.RemoveField(
            model_name='alevi',
            name='customer_care_specialist',
        ),
        migrations.RemoveField(
            model_name='cygnusinvestmentseller',
            name='customer_care_specialist',
        ),
        migrations.RemoveField(
            model_name='dreamcloudbuyland',
            name='customer_care_specialist',
        ),
        migrations.RemoveField(
            model_name='dreamweaverproperty',
            name='customer_care_specialist',
        ),
        migrations.RemoveField(
            model_name='franklinmanagement',
            name='customer_care_specialist',
        ),
        migrations.DeleteModel(
            name='FranklinSpiels',
        ),
        migrations.RemoveField(
            model_name='landquestpro',
            name='customer_care_specialist',
        ),
        migrations.RemoveField(
            model_name='landrapid',
            name='customer_care_specialist',
        ),
        migrations.RemoveField(
            model_name='lgpropertyventures',
            name='customer_care_specialist',
        ),
        migrations.RemoveField(
            model_name='libertylands',
            name='customer_care_specialist',
        ),
        migrations.RemoveField(
            model_name='lynkcapital',
            name='customer_care_specialist',
        ),
        migrations.RemoveField(
            model_name='newleafinvestors',
            name='customer_care_specialist',
        ),
        migrations.RemoveField(
            model_name='officeflowersvalleyproperties',
            name='customer_care_specialist',
        ),
        migrations.RemoveField(
            model_name='solidworkproperties',
            name='customer_care_specialist',
        ),
        migrations.DeleteModel(
            name='AffordableLandInvestment',
        ),
        migrations.DeleteModel(
            name='Alevi',
        ),
        migrations.DeleteModel(
            name='CygnusInvestmentSeller',
        ),
        migrations.DeleteModel(
            name='DreamCloudBuyLand',
        ),
        migrations.DeleteModel(
            name='DreamWeaverProperty',
        ),
        migrations.DeleteModel(
            name='FranklinManagement',
        ),
        migrations.DeleteModel(
            name='LandQuestPro',
        ),
        migrations.DeleteModel(
            name='LandRapid',
        ),
        migrations.DeleteModel(
            name='LGPropertyVentures',
        ),
        migrations.DeleteModel(
            name='LibertyLands',
        ),
        migrations.DeleteModel(
            name='LynkCapital',
        ),
        migrations.DeleteModel(
            name='NewLeafInvestors',
        ),
        migrations.DeleteModel(
            name='OfficeFlowersValleyProperties',
        ),
        migrations.DeleteModel(
            name='SolidWorkProperties',
        ),
    ]
