# Generated by Django 2.1.2 on 2019-03-25 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_added_all_seller_forms'),
        ('seller', '0002_auto_20190325_1342'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AfforableLandInvestment',
            new_name='AffordaleLandInvestment',
        ),
    ]
