# Generated by Django 2.1.2 on 2019-03-25 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_added_all_seller_forms'),
        ('seller', '0003_auto_20190325_1449'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LGPropertyVentrues',
            new_name='LGPropertyVentures',
        ),
        migrations.AlterModelOptions(
            name='affordalelandinvestment',
            options={'verbose_name': 'Affordable Land Investment Seller Data', 'verbose_name_plural': 'Affordable Land Investment Seller Datas'},
        ),
    ]
