# Generated by Django 2.1.2 on 2019-04-30 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_auto_20190325_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lynkcapital',
            old_name='leter',
            new_name='letter',
        ),
    ]
