# Generated by Django 2.1.2 on 2019-05-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_added_spiel_for_lynk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lynkcapital',
            options={'verbose_name': 'Lynk Capital Seller Data', 'verbose_name_plural': 'Lynk Capital Seller Datas'},
        ),
        migrations.AddField(
            model_name='lynkcapital',
            name='faq',
            field=models.TextField(blank=True, null=True, verbose_name='FAQ'),
        ),
    ]
