# Generated by Django 2.1.2 on 2019-05-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_added_spiel_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='franklinmanagement',
            name='closing_spiel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franklinmanagement',
            name='opening_spiel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
