# Generated by Django 2.1.2 on 2019-05-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_added_spiel_for_franklin'),
    ]

    operations = [
        migrations.AddField(
            model_name='newleafinvestors',
            name='closing_spiel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newleafinvestors',
            name='opening_spiel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
