# Generated by Django 2.1.2 on 2019-05-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_added_spiel_for_newleaf'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeflowersvalleyproperties',
            name='closing_spiel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officeflowersvalleyproperties',
            name='opening_spiel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lynkcapital',
            name='currently_listed',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], help_text='Are you the person that is currently listed on the deed as the owner on the county records? Y/N (Just enter the callers answer in answer field.)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lynkcapital',
            name='paved_or_dirt',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], help_text='Is the road Paved or Dirt? Y/N', max_length=10, null=True),
        ),
    ]
