# Generated by Django 2.1.2 on 2019-05-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_added_spiel_flowers'),
    ]

    operations = [
        migrations.AddField(
            model_name='alevi',
            name='closing_spiel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alevi',
            name='opening_spiel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alevi',
            name='optional_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alevi',
            name='back_taxes',
            field=models.CharField(blank=True, help_text='And do you own it free and clear or are there any back taxes on it? (if there are back taxes ask if they know the amount)', max_length=150, null=True),
        ),
    ]
