# Generated by Django 2.1.2 on 2019-05-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0012_added_spiel_for_alevi'),
    ]

    operations = [
        migrations.AddField(
            model_name='affordalelandinvestment',
            name='closing_spiel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='affordalelandinvestment',
            name='opening_spiel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
