# Generated by Django 2.1.2 on 2019-06-03 09:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0013_added_spiel_for_affordable'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffordableLandSpiels',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opening_spiel', models.TextField(blank=True, null=True)),
                ('closing_spiel', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='affordalelandinvestment',
            name='closing_spiel',
        ),
        migrations.RemoveField(
            model_name='affordalelandinvestment',
            name='opening_spiel',
        ),
    ]
