# Generated by Django 2.1.2 on 2019-06-03 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0014_added_model_for_spiel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affordablelandspiels',
            options={'ordering': ['-opening_spiel'], 'verbose_name': 'Affordable Land Investment Spiel', 'verbose_name_plural': 'Affordable Land Investment Spiels'},
        ),
    ]
