# Generated by Django 2.1.2 on 2019-06-05 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_added_all_seller_forms'),
        ('seller', '0015_auto_20190603_1918'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AffordaleLandInvestment',
            new_name='AffordableLandInvestment',
        ),
    ]
