# Generated by Django 2.1.2 on 2019-06-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0016_auto_20190605_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranklinSpiels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_spiel', models.TextField(blank=True, null=True)),
                ('closing_spiel', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Franklin Management Spiel',
                'verbose_name_plural': 'Franklin Management Spiels',
            },
        ),
        migrations.RemoveField(
            model_name='franklinmanagement',
            name='closing_spiel',
        ),
        migrations.RemoveField(
            model_name='franklinmanagement',
            name='opening_spiel',
        ),
    ]
