# Generated by Django 2.1.2 on 2018-10-30 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_auto_20181029_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('due_date', models.DateField()),
                ('client_code', models.CharField(max_length=250)),
                ('job_request_title', models.CharField(default='Give me a title later', max_length=250)),
                ('job_request_sent_via', models.CharField(max_length=250)),
                ('job_request_instruction', models.TextField()),
                ('total_hours_minutes_allocated', models.DecimalField(decimal_places=2, max_digits=4)),
                ('VA_admin_support', models.CharField(max_length=250)),
                ('status_of_the_job_request', models.CharField(choices=[('FOR FINAL REVIEW', 'For Final Review'), ('JOB REQUEST SENT TO VA', 'Job Request sent to VA'), ('IN PROGRESS', 'In Progress'), ('COMPLETE', 'Complete')], default='----', max_length=250)),
                ('notes_and_coaching_from_project_manager', models.TextField()),
                ('project_managers', models.ForeignKey(default='Gillian', on_delete=django.db.models.deletion.PROTECT, to='client.ProjectManager')),
            ],
        ),
    ]
