# Generated by Django 2.1.2 on 2018-11-25 02:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('client_code', models.CharField(max_length=250)),
                ('job_request_title', models.CharField(default='Give me a title later', max_length=250)),
                ('job_request_sent_via', models.CharField(max_length=250)),
                ('job_request_instruction', models.TextField()),
                ('total_hours_minutes_allocated', models.CharField(max_length=100)),
                ('VA_admin_support', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('in-progress', 'In Progress'), ('for-final-review', 'For Final Review'), ('job-request-sent-to-va', 'Job Request Sent to VA')], default='----', max_length=100)),
                ('notes_and_coaching_from_project_manager', models.TextField()),
                ('project_managers', models.ForeignKey(default='Gillian', on_delete=django.db.models.deletion.PROTECT, to='client.ProjectManager')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
