# Generated by Django 2.1.2 on 2019-07-15 13:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fillables', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_to_request', models.CharField(blank=True, choices=[('General Administrative Task', 'General Administrative Task'), ('Data Entry', 'Data Entry'), ('Website Design', 'Website Design'), ('Graphics Design', 'Graphics Design'), ('Customer Support', 'Customer Support'), ('Creating Ad Content', 'Creating Ad Content'), ('Marketing', 'Marketing'), ('Due Diligence', 'Due Diligence'), ('Craigslist Support', 'Craigslist Support')], max_length=150, null=True)),
                ('category', models.CharField(blank=True, choices=[('General Administrative Task', 'General Administrative Task'), ('Data Entry', 'Data Entry'), ('Website Design', 'Website Design'), ('Graphics Design', 'Graphics Design'), ('Customer Support', 'Customer Support'), ('Creating Ad Content', 'Creating Ad Content'), ('Marketing', 'Marketing'), ('Due Diligence', 'Due Diligence'), ('Craigslist Support', 'Craigslist Support')], max_length=150, null=True)),
                ('date_requested', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('month', models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=150, null=True)),
                ('requestors_name', models.CharField(blank=True, max_length=250, null=True)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('job_request_title', models.CharField(blank=True, max_length=150, null=True)),
                ('job_request_instruction', models.TextField(blank=True, null=True)),
                ('additional_comments_or_feedbacks', models.TextField(blank=True, null=True)),
                ('project_status', models.CharField(blank=True, choices=[('Sent to Project Manager', 'Sent to Project Manager'), ('Sent to Virtual Assistant', 'Sent to Virtual Assistant'), ('In Progress / PROCESSING', 'In Progress / PROCESSING'), ('Job Request Completed - VA Side', 'Job Request Completed - VA Side'), ('Submit to Project Manager for Quality Purposes', 'Submit to Project Manager for Quality Purposes'), ('Submit to Client', 'Submit to Client'), ('Job Request Completed', 'Job Request Completed')], max_length=150, null=True)),
                ('url_training_videos', models.CharField(blank=True, max_length=250, null=True)),
                ('manager_notes', models.TextField(blank=True, null=True)),
                ('client_notes', models.TextField(blank=True, null=True)),
                ('va_notes', models.TextField(blank=True, null=True)),
                ('authorized_minutes_hours_allocation', models.TextField(blank=True, null=True)),
                ('assigned_project_managers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PMs', to='users.Staffs')),
                ('assigned_va', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VAs', to='users.Staffs')),
                ('company_tagging', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.InternalCompanyName')),
            ],
            options={
                'ordering': ['-date_requested'],
            },
        ),
        migrations.CreateModel(
            name='JobRequestTimeSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_in', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('time_out', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('total_minutes_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Clients')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timesheet', to='jobrequest.JobRequest')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Staffs')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
