# Generated by Django 2.1.2 on 2019-08-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='company_tagging',
            field=models.CharField(blank=True, choices=[('landmaster.us', 'landmaster.us'), ('gpgcorporation.com', 'gpgcorporation.com'), ('callme.com.ph', 'callme.com.ph'), ('virtualExpressServices.com', 'virtualExpressServices.com'), ('creatif-designs.com', 'creatif-designs.com'), ('vacantpropertiesglobal.com', 'vacantpropertiesglobal.com')], max_length=150, null=True),
        ),
    ]
