# Generated by Django 2.1.2 on 2019-03-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='status',
            field=models.CharField(choices=[('----', '------'), ('Complete', 'Complete'), ('in Progress', 'In Progress'), ('For Final Review', 'For Final Review'), ('Job Request Sent to VA', 'Job Request Sent to VA')], default='----', max_length=100),
        ),
    ]
