# Generated by Django 2.1.2 on 2018-11-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequest', '0002_auto_20181108_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
