# Generated by Django 2.1.2 on 2018-12-05 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequest', '0002_auto_20181205_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobrequest',
            options={'ordering': ['-date'], 'permissions': (('can_view', 'Can view job request'), ('can_add', 'Can add job request'), ('can_change', 'Can change job request'), ('can_delete', 'Can delete job request'))},
        ),
    ]
