# Generated by Django 2.1.2 on 2019-03-27 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fillables', '0002_added_va'),
        ('jobrequest', '0002_updated_status_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobrequest',
            options={'ordering': ['-date_requested']},
        ),
        migrations.RenameField(
            model_name='jobrequest',
            old_name='notes_and_coaching_from_project_manager',
            new_name='additional_comments_or_feedbacks',
        ),
        migrations.RenameField(
            model_name='jobrequest',
            old_name='project_managers',
            new_name='assigned_project_managers',
        ),
        migrations.RenameField(
            model_name='jobrequest',
            old_name='date',
            new_name='date_requested',
        ),
        migrations.RenameField(
            model_name='jobrequest',
            old_name='VA_admin_support',
            new_name='job_request_number',
        ),
        migrations.RenameField(
            model_name='jobrequest',
            old_name='job_request_sent_via',
            new_name='requestors_name',
        ),
        migrations.RemoveField(
            model_name='jobrequest',
            name='client_code',
        ),
        migrations.RemoveField(
            model_name='jobrequest',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='jobrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='jobrequest',
            name='total_hours_minutes_allocated',
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='assigned_va',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.VirtualAssistant'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='category',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='client_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='manager_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='month',
            field=models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='project_status',
            field=models.CharField(blank=True, choices=[('Sent to Project Manager', 'Sent to Project Manager'), ('Sent to Virtual Assistant', 'Sent to Virtual Assistant'), ('In Progress / PROCESSING', 'In Progress / PROCESSING'), ('Job Request Completed - VA Side', 'Job Request Completed - VA Side'), ('Submit to Project Manager for Quality Purposes', 'Submit to Project Manager for Quality Purposes'), ('Submit to Client', 'Submit to Client'), ('Job Request Completed', 'Job Request Completed')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='time_in',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='time_out',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='total_minutes_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='url_training_videos',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='va_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='job_request_instruction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='job_request_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
