# Generated by Django 2.1.2 on 2019-07-11 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequest', '0002_auto_20190622_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='assigned_project_managers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Staffs'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='url_training_videos',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
