# Generated by Django 2.1.2 on 2018-12-05 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequest', '0003_auto_20181205_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobrequest',
            options={'ordering': ['-date'], 'permissions': (('can_view', 'Can view a job request'), ('can_add', 'Can add a job request'), ('can_change', 'Can change a job request'), ('can_delete', 'Can delete a job request'))},
        ),
    ]
