# Generated by Django 2.1.2 on 2018-11-08 08:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequest', '0003_auto_20181108_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOfTheJobRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_of_status', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='status_of_the_job_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobrequest.StatusOfTheJobRequest'),
        ),
    ]
