# Generated by Django 2.1.2 on 2019-08-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequest', '0003_auto_20190827_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrequest',
            old_name='additional_mem0',
            new_name='additional_memo',
        ),
    ]
