# Generated by Django 2.1.2 on 2018-12-05 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequest', '0004_auto_20181205_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobrequest',
            options={},
        ),
    ]
