# Generated by Django 2.1.2 on 2018-11-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequest', '0004_auto_20181108_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='total_hours_minutes_allocated',
            field=models.CharField(max_length=100),
        ),
    ]
