# Generated by Django 2.1.2 on 2019-07-11 07:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequest', '0004_auto_20190711_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequestTimeSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_in', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('time_out', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('total_minutes_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='jobrequest',
            name='time_in',
        ),
        migrations.RemoveField(
            model_name='jobrequest',
            name='time_out',
        ),
        migrations.RemoveField(
            model_name='jobrequest',
            name='total_minutes_hours',
        ),
        migrations.AddField(
            model_name='jobrequesttimesheet',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobrequest.JobRequest'),
        ),
    ]
