# Generated by Django 2.1.2 on 2019-04-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequest', '0004_auto_20190329_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='company_to_request',
            field=models.CharField(blank=True, choices=[('General Administrative Task', 'General Administrative Task'), ('Data Entry', 'Data Entry'), ('Website Design', 'Website Design'), ('Graphics Design', 'Graphics Design'), ('Customer Support', 'Customer Support'), ('Creating Ad Content', 'Creating Ad Content'), ('Marketing', 'Marketing'), ('Due Diligence', 'Due Diligence'), ('Craigslist Support', 'Craigslist Support')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='category',
            field=models.CharField(blank=True, choices=[('General Administrative Task', 'General Administrative Task'), ('Data Entry', 'Data Entry'), ('Website Design', 'Website Design'), ('Graphics Design', 'Graphics Design'), ('Customer Support', 'Customer Support'), ('Creating Ad Content', 'Creating Ad Content'), ('Marketing', 'Marketing'), ('Due Diligence', 'Due Diligence'), ('Craigslist Support', 'Craigslist Support')], max_length=150, null=True),
        ),
    ]
