# Generated by Django 2.1.2 on 2018-11-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequest', '0005_auto_20181109_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobrequest',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='status_of_the_job_request',
            field=models.CharField(choices=[('COMPLETE', 'Complete'), ('IN PROGRESS', 'In Progress'), ('FOR FINAL REVIEW', 'For Final Review'), ('JOB REQUEST SENT TO VA', 'Job Request Sent to VA')], max_length=100),
        ),
        migrations.DeleteModel(
            name='StatusOfTheJobRequest',
        ),
    ]
