# Generated by Django 2.1.2 on 2019-07-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequest', '0005_auto_20190711_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequesttimesheet',
            name='staff',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
