# Generated by Django 2.1.2 on 2018-12-05 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequest', '0005_auto_20181205_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobrequest',
            options={'ordering': ['-date']},
        ),
    ]
