# Generated by Django 2.1.4 on 2019-04-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequest', '0005_auto_20190416_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrequest',
            old_name='company_assigned_to',
            new_name='company_tagging',
        ),
        migrations.RemoveField(
            model_name='jobrequest',
            name='company_billable_to',
        ),
        migrations.RemoveField(
            model_name='jobrequest',
            name='job_request_number',
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
