# Generated by Django 2.1.4 on 2019-04-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequest', '0006_auto_20190422_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='authorized_minutes_hours_allocation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
