# Generated by Django 2.1.2 on 2018-11-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequest', '0006_auto_20181119_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='status_of_the_job_request',
            field=models.CharField(choices=[('Complete', 'Complete'), ('In Progress', 'In Progress'), ('For Final Review', 'For Final Review'), ('Job Request Sent to VA', 'Job Request Sent to VA')], max_length=100),
        ),
    ]
