# Generated by Django 2.1.2 on 2019-07-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequest', '0006_jobrequesttimesheet_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequesttimesheet',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
