# Generated by Django 2.1.4 on 2019-04-22 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequest', '0007_jobrequest_authorized_minutes_hours_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='time_in',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='time_out',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='total_minutes_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
