# Generated by Django 2.1.2 on 2019-07-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequest', '0007_jobrequesttimesheet_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequesttimesheet',
            name='client',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
