# Generated by Django 2.1.2 on 2019-07-15 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequest', '0008_jobrequesttimesheet_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequesttimesheet',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timesheet', to='jobrequest.JobRequest'),
        ),
    ]
