# Generated by Django 2.1.2 on 2019-07-15 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequest', '0010_auto_20190715_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequesttimesheet',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Clients', to='users.Clients'),
        ),
        migrations.AlterField(
            model_name='jobrequesttimesheet',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Staffs', to='users.Staffs'),
        ),
    ]
