# Generated by Django 2.1.2 on 2019-06-13 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerreminders',
            old_name='notes_from_company',
            new_name='memo_from_requestor',
        ),
        migrations.RenameField(
            model_name='managerreminders',
            old_name='manager_under',
            new_name='requestor',
        ),
        migrations.RemoveField(
            model_name='managerreminders',
            name='notes_from_manager',
        ),
        migrations.AddField(
            model_name='managerreminders',
            name='memo_from_requestee',
            field=models.TextField(blank=True, default='Memo will be in a minute or two.', null=True),
        ),
        migrations.AddField(
            model_name='managerreminders',
            name='requestee_for_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Clients'),
        ),
        migrations.AddField(
            model_name='managerreminders',
            name='requestee_for_staffs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Staffs'),
        ),
        migrations.AlterField(
            model_name='managerreminders',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Processing', 'Processing'), ('In Review', 'In Review'), ('Completed', 'Completed')], max_length=150, null=True),
        ),
    ]
