# Generated by Django 2.1.2 on 2019-06-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_auto_20190613_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerreminders',
            name='description',
        ),
        migrations.AddField(
            model_name='managerreminders',
            name='additional_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerreminders',
            name='comment_from_admin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
