# Generated by Django 2.1.2 on 2019-06-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_auto_20190614_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerreminders',
            old_name='additional_comment',
            new_name='additional_comment_requestee_client',
        ),
        migrations.AddField(
            model_name='managerreminders',
            name='additional_comment_requestee_staff',
            field=models.TextField(blank=True, null=True),
        ),
    ]
