# Generated by Django 2.1.2 on 2019-06-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0005_auto_20190614_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerreminders',
            name='requestee_for_client',
        ),
        migrations.RemoveField(
            model_name='managerreminders',
            name='requestee_for_staffs',
        ),
        migrations.AddField(
            model_name='managerreminders',
            name='requestee',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
