# Generated by Django 2.1.2 on 2019-06-17 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0006_auto_20190614_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managerreminders',
            options={'ordering': ['-date'], 'verbose_name': 'General Reminder', 'verbose_name_plural': 'General Reminders'},
        ),
    ]
