# Generated by Django 2.1.2 on 2019-09-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adscontent',
            name='content_status',
            field=models.CharField(choices=[('Client Submitted to the Ad/s Writer', 'Client Submitted to the Ad/s Writer'), ('Ad/s Writer Processing', 'Ad/s Writer Processing'), ('Ad/s Content Completed', 'Ad/s Content Completed'), ('Ad/s Content Submitted to the Client', 'Ad/s Content Submitted to the Client'), ('Ad/s Content Closed', 'Ad/s Content Closed')], max_length=150),
        ),
    ]
