# Generated by Django 2.1.2 on 2019-09-26 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20190924_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adscontent',
            name='ads_writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Staffs'),
        ),
        migrations.AlterField(
            model_name='adscontent',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Clients'),
        ),
    ]
