# Generated by Django 2.1.2 on 2019-06-26 08:28

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_requested', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_completed', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('type_of_marketing_sites', models.CharField(blank=True, choices=[('LandModo', 'LandModo'), ('Zillow', 'Zillow'), ('Craigslist', 'Craigslist'), ('Facebook MarketPlace', 'Facebook MarketPlace'), ('KSL.com', 'KSL.com'), ('Ultimate Land Listings', 'Ultimate Land Listings'), ('LandCentury', 'LandCentury'), ('Landhub', 'Landhub'), ('Lands of America', 'Lands of America'), ('Landpin', 'Landpin'), ('Landwatch', 'Landwatch'), ('Landflip', 'Landflip'), ('Others', 'Others')], max_length=150, null=True)),
                ('indicate_others', models.CharField(blank=True, max_length=150, null=True)),
                ('client_full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('client_company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('apn', models.CharField(blank=True, max_length=150, null=True)),
                ('title_of_the_post', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=150, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('url_link', models.URLField(blank=True, null=True)),
                ('marketing_associate', models.CharField(blank=True, max_length=150, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('post_for_approval', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Pending for Approval', 'Pending for Approval')], max_length=150, null=True)),
                ('status', models.CharField(blank=True, choices=[('In progress', 'In progress'), ('Complete', 'Complete')], default=0, max_length=150, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('notes_from_the_client', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Marketing Sites Inventory',
                'verbose_name_plural': 'Marketing Sites Inventories',
                'ordering': ['-date_requested'],
            },
        ),
    ]
