# Generated by Django 2.1.2 on 2019-08-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingsites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='apn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='title_of_the_post',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='url_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
