# Generated by Django 2.1.2 on 2019-09-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingsites', '0002_auto_20190805_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='indicate_others',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='post_for_approval',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Pending for Approval', 'Pending for Approval'), ('Waived by the Client', 'Waived by the Client')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='type_of_marketing_sites',
            field=models.CharField(blank=True, choices=[('LandModo', 'LandModo'), ('Zillow', 'Zillow'), ('Craigslist', 'Craigslist'), ('Facebook MarketPlace', 'Facebook MarketPlace'), ('KSL.com', 'KSL.com'), ('Ultimate Land Listings', 'Ultimate Land Listings'), ('LandCentury', 'LandCentury'), ('Landhub', 'Landhub'), ('Lands of America', 'Lands of America'), ('Landpin', 'Landpin'), ('Landwatch', 'Landwatch'), ('Landflip', 'Landflip'), ('Multiple Sites', 'Multiple Sites'), ('Others', 'Others')], max_length=150, null=True),
        ),
    ]
