# Generated by Django 2.1.2 on 2019-04-09 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='username',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='user_name',
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.DeleteModel(
            name='Staffs',
        ),
    ]
