# Generated by Django 2.1.2 on 2019-06-11 14:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.CharField(max_length=150)),
                ('category', models.CharField(blank=True, max_length=150, null=True)),
                ('tagging', models.CharField(blank=True, choices=[('One Time', 'One Time'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], max_length=150, null=True)),
                ('next_due_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=100, null=True)),
                ('payment_channel', models.CharField(blank=True, max_length=150, null=True)),
                ('referrence', models.CharField(blank=True, max_length=150, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Company Expense',
                'verbose_name_plural': 'Company Expenses',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.AddField(
            model_name='expenses',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='companyexpenses.Type'),
        ),
    ]
