# Generated by Django 2.1.2 on 2019-05-12 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyexpenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'ordering': ['-date'], 'verbose_name': 'Company Expense', 'verbose_name_plural': 'Company Expenses'},
        ),
    ]
