# Generated by Django 2.1.2 on 2019-08-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyexpenses', '0002_auto_20190823_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='company_tagging',
            field=models.CharField(blank=True, choices=[('landmaster.us', 'landmaster.us'), ('gpgcorporation.com', 'gpgcorporation.com'), ('callme.com.ph', 'callme.com.ph'), ('virtualExpressServices.com', 'virtualExpressServices.com'), ('creatif-designs.com', 'creatif-designs.com'), ('vacantpropertiesglobal.com', 'vacantpropertiesglobal.com')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='month',
            field=models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=100, null=True),
        ),
    ]
