# Generated by Django 2.1.2 on 2018-10-29 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientName',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField()),
                ('month_to_date', models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sept', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=10)),
                ('title_of_job_request', models.CharField(max_length=250)),
                ('job_request_description', models.TextField()),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('duration', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total_items_finished', models.IntegerField()),
                ('addtional_comments', models.TextField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('approval_from_project_manager', models.CharField(choices=[('APPROVED', 'Approved'), ('FOR REVIEW', 'For Review')], max_length=100)),
                ('approval_of_admin', models.CharField(choices=[('APPROVED', 'Approved'), ('FOR REVIEW', 'For Review')], max_length=100)),
                ('assigned_job_request_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('clients_full_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reporting.ClientName')),
                ('job_requested_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reporting.Job')),
            ],
        ),
        migrations.CreateModel(
            name='WeekToDate',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('weeks', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='week_to_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reporting.WeekToDate'),
        ),
    ]
