# Generated by Django 2.1.2 on 2018-11-25 02:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField()),
                ('month_to_date', models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sept', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=10)),
                ('title_of_job_request', models.CharField(max_length=250)),
                ('job_request_description', models.TextField()),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('duration', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total_items_finished', models.IntegerField()),
                ('additional_comments', models.TextField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('approval_from_project_manager', models.CharField(choices=[('APPROVED', 'Approved'), ('FOR REVIEW', 'For Review')], max_length=100)),
                ('approval_of_admin', models.CharField(choices=[('APPROVED', 'Approved'), ('FOR REVIEW', 'For Review')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WeekToDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weeks', models.CharField(max_length=250)),
            ],
        ),
    ]
