# Generated by Django 2.1.2 on 2018-12-24 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fillables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VATimeSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField()),
                ('month_to_date', models.CharField(blank=True, choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sept', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=10, null=True)),
                ('title_of_job_request', models.CharField(blank=True, max_length=250, null=True)),
                ('job_request_description', models.TextField(blank=True, null=True)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('total_items_finished', models.IntegerField(blank=True, null=True)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('approval_from_project_manager', models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('FOR REVIEW', 'For Review')], max_length=100, null=True)),
                ('approval_of_admin', models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('FOR REVIEW', 'For Review')], max_length=100, null=True)),
                ('assigned_job_request_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('clients_full_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.CompanyName')),
                ('date_information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.DateInformation')),
                ('list_of_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.Task')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.ProjectManager')),
            ],
            options={
                'verbose_name': 'VA Time Sheet',
                'verbose_name_plural': 'VA Time Sheets',
                'ordering': ['clients_full_name'],
            },
        ),
    ]
