# Generated by Django 2.1.2 on 2019-06-11 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reporting', '0001_initial'),
        ('fillables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vatimesheet',
            name='assigned_job_request_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vatimesheet',
            name='clients_full_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.CompanyName'),
        ),
        migrations.AddField(
            model_name='vatimesheet',
            name='date_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.DateInformation'),
        ),
        migrations.AddField(
            model_name='vatimesheet',
            name='list_of_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.Task'),
        ),
        migrations.AddField(
            model_name='vatimesheet',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.ProjectManager'),
        ),
    ]
