# Generated by Django 2.1.2 on 2018-10-29 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='addtional_comments',
            new_name='additional_comments',
        ),
    ]
