# Generated by Django 2.1.2 on 2018-12-05 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_auto_20181125_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'permissions': (('can_view', 'Can view report'), ('can_add', 'Can add report'), ('can_change', 'Can change report'), ('can_delete', 'Can delete report'))},
        ),
    ]
