# Generated by Django 2.1.2 on 2018-10-30 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20181029_1237'),
        ('reporting', '0003_auto_20181029_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.ProjectManager'),
        ),
    ]
