# Generated by Django 2.1.2 on 2018-11-19 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_report_project_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='clients_full_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.ClientName'),
        ),
        migrations.DeleteModel(
            name='ClientName',
        ),
    ]
