# Generated by Django 2.1.2 on 2019-06-18 10:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('callmeinventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-transferred_date'], 'verbose_name': 'Call Me Inventory', 'verbose_name_plural': 'Call Me Inventories'},
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='total_handling_time',
            new_name='call_duration',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='date_of_call',
            new_name='date_lead_received',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='mobile',
            new_name='full_name_of_lead',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='category',
            new_name='type_of_form',
        ),
        migrations.AddField(
            model_name='inventory',
            name='customer_representative',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Staffs'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='financial_status',
            field=models.CharField(blank=True, choices=[('Billed', 'Billed'), ('Unbilled', 'Unbilled'), ('Waived', 'Waived')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='phone_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Transferred to Podio - Personal Account', 'Transferred to Podio - Personal Account'), ('Transferred to Land Speed', 'Transferred to Land Speed'), ('Transferred to Investment Dominator ', 'Transferred to Investment Dominator '), ('Airtable ', 'Airtable '), ('Others', 'Others')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='transferred_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
