# Generated by Django 2.1.2 on 2019-06-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callmeinventory', '0003_added_id_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='customer_representative',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
