# Generated by Django 2.1.2 on 2019-06-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callmeinventory', '0004_changed_the_models_for_csr'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='lead_transferred_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
