# Generated by Django 2.1.2 on 2019-06-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callmeinventory', '0006_auto_20190619_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='total_mins',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
