# Generated by Django 2.1.2 on 2019-06-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callmeinventory', '0007_auto_20190619_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='type_of_form',
            field=models.CharField(blank=True, choices=[('Buyers', 'Buyers'), ('Sellers', 'Sellers'), ('General Call', 'General Call'), ('Voicemail', 'Voicemail'), ('Property Management', 'Property Management'), ('Others', 'Others')], max_length=150, null=True),
        ),
    ]
