# Generated by Django 2.1.2 on 2019-06-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callmeinventory', '0010_auto_20190630_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='call_duration',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='total_time_transferring_leads',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
