# Generated by Django 2.1.2 on 2019-07-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callmeinventory', '0011_auto_20190630_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
