# Generated by Django 2.1.2 on 2019-07-03 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callmeinventory', '0012_auto_20190702_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='crm_login',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='phone_login',
        ),
    ]
