# Generated by Django 2.1.2 on 2019-07-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callmeinventory', '0013_auto_20190703_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='lead_conversion',
            field=models.CharField(blank=True, choices=[('Interested', 'Interested'), ('Not Interested', 'Not Interested'), ('Dead Lead', 'Dead Lead'), ('Others', 'Others')], max_length=150, null=True),
        ),
    ]
