# Generated by Django 2.1.2 on 2019-07-17 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callmeinventory', '0014_inventory_lead_conversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='client_company_name',
        ),
    ]
