# Generated by Django 2.1.2 on 2019-07-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callmeinventory', '0015_remove_inventory_client_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Transferred to Podio - Personal Account', 'Transferred to Podio - Personal Account'), ('Transferred to Land Speed', 'Transferred to Land Speed'), ('Transferred to Investment Dominator', 'Transferred to Investment Dominator'), ('Transferred to Buildium', 'Transferred to Buildium'), ('Airtable', 'Airtable'), ('Others', 'Others')], max_length=150, null=True),
        ),
    ]
