# Generated by Django 2.1.2 on 2019-06-11 14:29

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallMe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, help_text='Date of the call.', null=True)),
                ('category', models.CharField(blank=True, choices=[('Buyers', 'Buyers'), ('Sellers', 'Sellers'), ('General Call', 'General Call'), ('Voicemail', 'Voicemail')], max_length=150, null=True)),
                ('client_name', models.CharField(blank=True, help_text='Client Full name', max_length=150, null=True)),
                ('company_name', models.CharField(blank=True, help_text="Client's company name", max_length=150, null=True)),
                ('mobile', models.CharField(blank=True, help_text='Mobile number', max_length=150, null=True)),
                ('total_handling_time', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_transferring_leads', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_mins', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Call me Inventory',
                'verbose_name_plural': 'Call me Inventories',
                'ordering': ['-date'],
            },
        ),
    ]
