# Generated by Django 2.1.2 on 2019-06-11 14:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCareSpecialist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CygnusInvestment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_date', models.DateField(blank=True, null=True)),
                ('provided_contact_information', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10, verbose_name='Have you provided Mr. Temes with your contact information? (if yes, skip questions below, and take brief message) ')),
                ('address_of_property', models.TextField(blank=True, null=True, verbose_name='What is address of the property you are interested in? ')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='What is your name?')),
                ('agent', models.CharField(blank=True, max_length=250, null=True, verbose_name='Are you an agent?')),
                ('listing', models.CharField(blank=True, choices=[('LANDWATCH', 'Landwatch'), ('LANDPIN', 'Landpin'), ('LANDS OF AMERICA', 'Lands of America'), ('CRAIGSLIST', 'Craigslist'), ('LAND AND FARM', 'Land and Farm'), ('KSL', 'KSL'), ('ZILLOW', 'Zillow'), ('ULTIMATE LAND LISTINGS', 'Ultimate Land Listings'), ('LETGO', 'Letgo'), ('LANDHUB', 'Landhub'), ('LANDMODO', 'LandModo'), ('LANDSALELISTING', 'LandSaleListing'), ('ADLANDPRO', 'AdLandPro'), ('LANDCENTURY', 'LandCentury'), ('LANDFLIP', 'LandFlip'), ('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('INSTAGRAM', 'Instagram'), ('NEIGHBOR LETTER', 'Neighbor Letter'), ('EMAIL MARKERTING', 'Email Marketing')], max_length=250, null=True, verbose_name='Where did you see the listing?')),
                ('phone_number', models.CharField(blank=True, max_length=250, null=True, verbose_name="What's your phone number?")),
                ('email', models.EmailField(blank=True, max_length=250, null=True, verbose_name="What's your email address?")),
                ('handling_time', models.CharField(blank=True, max_length=250, null=True, verbose_name='Average handling time')),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('customer_care_specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='buyer.CustomerCareSpecialist')),
            ],
            options={
                'verbose_name': 'Cygnus Investment Buyer Data',
                'verbose_name_plural': 'Cygnus Investment Buyer Datas',
            },
        ),
        migrations.CreateModel(
            name='WeBuyAcreageLlc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_date', models.DateField(blank=True, null=True)),
                ('contact_information', models.CharField(blank=True, help_text='Have you provided (Jeff) with your contact information? (if yes, skip questions below, and take a brief message)', max_length=250, null=True)),
                ('address_or_apn', models.TextField(blank=True, help_text='What is the address of the property you are interested in?(If the caller does NOT have the property address, ask them...)What is the APN number?', null=True)),
                ('name_of_the_caller', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_number_of_caller', models.CharField(blank=True, max_length=250, null=True)),
                ('are_you_an_agent', models.CharField(blank=True, max_length=250, null=True)),
                ('listing', models.CharField(blank=True, help_text='Where did you see the listing?', max_length=250, null=True)),
                ('your_phone_number', models.CharField(blank=True, help_text='What is your Phone number?', max_length=250, null=True)),
                ('email_address', models.EmailField(blank=True, help_text='What is your email address', max_length=250, null=True)),
                ('average_handling_time', models.CharField(blank=True, help_text='Average Handling Time', max_length=250, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('customer_care_specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='buyer.CustomerCareSpecialist')),
            ],
            options={
                'verbose_name': 'We Buy Acreage LLC Buyer Data',
                'verbose_name_plural': 'We Buy Acreage LLC Buyer Data',
            },
        ),
    ]
