# Generated by Django 2.1.2 on 2019-06-19 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cygnusinvestment',
            name='customer_care_specialist',
        ),
        migrations.RemoveField(
            model_name='webuyacreagellc',
            name='customer_care_specialist',
        ),
        migrations.DeleteModel(
            name='CustomerCareSpecialist',
        ),
        migrations.DeleteModel(
            name='CygnusInvestment',
        ),
        migrations.DeleteModel(
            name='WeBuyAcreageLlc',
        ),
    ]
