# Generated by Django 2.1.2 on 2019-03-22 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_webuyacreagellc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cygnusinvestment',
            options={'verbose_name': 'Cygnus Investment Buyer Form', 'verbose_name_plural': 'Cygnus Investment Buyer Form'},
        ),
        migrations.AlterModelOptions(
            name='webuyacreagellc',
            options={'verbose_name': 'We Buy Acreage LLC Buyer Form', 'verbose_name_plural': 'We Buy Acreage LLC Buyer Form'},
        ),
        migrations.AlterField(
            model_name='webuyacreagellc',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
