# Generated by Django 2.1.2 on 2019-03-23 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_added_id_in_WeBuyAcreageLLC'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cygnusinvestment',
            options={'verbose_name': 'Cygnus Investment Buyer Data', 'verbose_name_plural': 'Cygnus Investment Buyer Datas'},
        ),
        migrations.AlterModelOptions(
            name='webuyacreagellc',
            options={'verbose_name': 'We Buy Acreage LLC Buyer Data', 'verbose_name_plural': 'We Buy Acreage LLC Buyer Data'},
        ),
    ]
