# Generated by Django 2.1.2 on 2019-03-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_calldetailsschema'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='CallDetailsSchema',
            new_name='FieldSchema',
        ),
    ]
