# Generated by Django 2.1.2 on 2019-03-10 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20190310_1556'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FieldSchema',
        ),
        migrations.DeleteModel(
            name='ModelSchema',
        ),
        migrations.AlterModelOptions(
            name='calldetails',
            options={'ordering': ['client_name'], 'verbose_name': 'Call Detail'},
        ),
    ]
