# Generated by Django 2.1.2 on 2019-03-11 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_fieldschema_modelschema'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FieldSchema',
        ),
        migrations.DeleteModel(
            name='ModelSchema',
        ),
    ]
