# Generated by Django 2.1.2 on 2019-04-17 06:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fillables', '0002_added_va'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaPayroll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('client_name', models.CharField(blank=True, max_length=150, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='Salary= Total hours * Hourly rate', max_digits=7, null=True)),
                ('virtual_assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.VirtualAssistant')),
            ],
            options={
                'verbose_name': 'VA Payroll',
                'verbose_name_plural': 'VA Payrolls',
                'ordering': ['date'],
            },
        ),
    ]
