# Generated by Django 2.1.2 on 2019-06-11 14:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fillables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaCashOut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_release', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('referrence', models.CharField(blank=True, max_length=150, null=True)),
                ('bank', models.CharField(blank=True, max_length=150, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=150, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.VirtualAssistant')),
            ],
            options={
                'verbose_name': 'VA Cash Out',
                'verbose_name_plural': 'VA Cash Outs',
                'ordering': ['-date_release'],
            },
        ),
        migrations.CreateModel(
            name='VaPayroll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('virtual_assistant', models.CharField(blank=True, max_length=150, null=True)),
                ('time_in', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('time_out', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('client_name', models.CharField(blank=True, max_length=150, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='Salary = Total hours * Hourly rate', max_digits=7, null=True)),
                ('status', models.CharField(blank=True, choices=[('APPROVED-BY-THE-MANAGER', 'Approved by the Manager'), ('HOURS-RE-ADJUSTMENT', 'Hours Re-Adjustment'), ('DECLINED', 'Declined')], max_length=150, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'VA Payroll',
                'verbose_name_plural': 'VA Payrolls',
                'ordering': ['-date'],
            },
        ),
    ]
