# Generated by Django 2.1.2 on 2019-04-17 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20190417_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vapayroll',
            name='hours',
        ),
    ]
