# Generated by Django 2.1.2 on 2019-04-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_auto_20190418_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vapayroll',
            name='virtual_assistant',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
