# Generated by Django 2.1.2 on 2019-04-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_auto_20190427_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='vapayroll',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vapayroll',
            name='status',
            field=models.CharField(blank=True, choices=[('APPROVED-BY-THE-MANAGER', 'Approved by the Manager'), ('HOURS-RE-ADJUSTMENT', 'Hours Re-Adjustment'), ('DECLINED', 'Declined')], max_length=150, null=True),
        ),
    ]
