# Generated by Django 2.1.2 on 2019-04-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_auto_20190429_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaCashOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_release', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('referrence', models.CharField(blank=True, max_length=150, null=True)),
                ('bank', models.CharField(blank=True, max_length=150, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=150, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'VA Cash Out',
                'verbose_name_plural': 'VA Cash Outs',
                'ordering': ['-date_release'],
            },
        ),
        migrations.AlterModelOptions(
            name='vapayroll',
            options={'ordering': ['-date'], 'verbose_name': 'VA Payroll', 'verbose_name_plural': 'VA Payrolls'},
        ),
    ]
