# Generated by Django 2.1.2 on 2019-04-30 07:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_auto_20190430_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacashout',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payroll.VaPayroll'),
        ),
        migrations.AlterField(
            model_name='vacashout',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
