# Generated by Django 2.1.2 on 2019-04-30 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_auto_20190430_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacashout',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.VirtualAssistant'),
        ),
    ]
