# Generated by Django 2.1.2 on 2019-07-05 08:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_company_name', models.CharField(max_length=150)),
                ('date_signed_up', models.DateField(blank=True, null=True)),
                ('first_day_of_call', models.DateField(blank=True, null=True)),
                ('first_billing_cycle', models.DateField(blank=True, null=True)),
                ('last_billing_cycle', models.DateField(blank=True, null=True)),
                ('type_of_plan', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total_minutes_used', models.DecimalField(decimal_places=2, max_digits=7)),
                ('excess_minutes', models.DecimalField(decimal_places=2, max_digits=7)),
                ('payment_made', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('transaction_number', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Waived', 'Waived')], max_length=150, null=True)),
                ('notes_inventory', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('notes_payment_made', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('client_full_name', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.Clients')),
            ],
            options={
                'ordering': ['-date_signed_up'],
            },
        ),
    ]
