# Generated by Django 2.1.2 on 2019-07-05 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callmefinancialreport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialreport',
            name='client_full_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Clients'),
        ),
    ]
