# Generated by Django 2.1.2 on 2019-07-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callmefinancialreport', '0002_auto_20190705_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialreport',
            name='excess_minutes',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='total_minutes_used',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
    ]
