# Generated by Django 2.1.2 on 2019-07-06 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('callmefinancialreport', '0003_auto_20190706_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreport',
            name='date_created',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='date_paid',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='date_signed_up',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
