# Generated by Django 2.1.2 on 2019-07-11 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist', '0002_craiglistposting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craiglistposting',
            name='cl_admin_support',
        ),
        migrations.DeleteModel(
            name='CraiglistPosting',
        ),
    ]
