# Generated by Django 2.1.2 on 2019-05-13 09:06

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clienttimesheet', '0002_auto_20190513_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, help_text='Date the payment made.', null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('reference', models.CharField(blank=True, max_length=150, null=True)),
                ('payment_channel', models.CharField(blank=True, max_length=150, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Payment Made for the Client',
                'verbose_name_plural': 'Payment Made for the Clients',
                'ordering': ['-date'],
            },
        ),
    ]
