# Generated by Django 2.1.2 on 2019-05-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienttimesheet', '0003_paymentmade'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmade',
            name='client_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
