# Generated by Django 2.1.2 on 2019-07-25 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clienttimesheet', '0003_auto_20190725_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='clients_full_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Clients'),
        ),
    ]
