# Generated by Django 2.1.2 on 2019-05-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienttimesheet', '0004_paymentmade_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Not Approved', 'Approved')], default='Approved', max_length=50),
        ),
    ]
