# Generated by Django 2.1.2 on 2019-07-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienttimesheet', '0005_related_money_fields_changed_to_moneyfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='hourly_rate_peso_currency',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='hourly_rate_usd_currency',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='paypal_charge_currency',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='total_amount_due_currency',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='total_charge_peso_currency',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='total_charge_usd_currency',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='total_charge_with_paypal_currency',
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='hourly_rate_peso',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='hourly_rate_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='paypal_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='total_amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='total_charge_peso',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='total_charge_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='total_charge_with_paypal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True),
        ),
    ]
