# Generated by Django 2.1.2 on 2019-07-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienttimesheet', '0006_returned_to_decimal_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='paypal_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='total_amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='total_charge_with_paypal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
    ]
