# Generated by Django 2.1.2 on 2019-07-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienttimesheet', '0007_max_digits_to_7'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='paypal_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.05, max_digits=7, null=True),
        ),
    ]
