# Generated by Django 2.1.2 on 2019-07-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienttimesheet', '0008_changed_default_for_pp_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='job_request_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
