# Generated by Django 2.1.2 on 2019-07-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienttimesheet', '0009_changed_to_text_field_for_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='first_month_to_date',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='second_month_to_date',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='month_to_date',
            field=models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=150, null=True),
        ),
    ]
