# Generated by Django 2.1.2 on 2019-07-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienttimesheet', '0010_returned_month_to_date_to_monts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashout',
            name='rcbc',
        ),
        migrations.AddField(
            model_name='cashout',
            name='payment_channel',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='admin_approval',
            field=models.CharField(choices=[('Approved', 'Approved'), ('For Review', 'For Review'), ('Declined', 'Declined'), ('Dispute', 'Dispute'), ('Waived', 'Waived')], default='For Review', max_length=50),
        ),
    ]
