# Generated by Django 2.1.2 on 2019-07-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienttimesheet', '0012_added_bonus_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='admin_approval',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('For Review', 'For Review'), ('Declined', 'Declined'), ('Dispute', 'Dispute'), ('Waived', 'Waived')], default='For Review', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('For Review', 'For Review'), ('Dispute', 'Dispute'), ('Waived', 'Waived')], default='For Review', max_length=50, null=True),
        ),
    ]
