# Generated by Django 2.1.2 on 2019-08-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienttimesheet', '0013_added_null_blank_in_status_admin_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='admin_approval',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('For Review', 'For Review'), ('Declined', 'Declined'), ('Dispute', 'Dispute'), ('Waived', 'Waived')], default='Submitted', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Submitted', 'Submitted'), ('Pre-Approved by the Manager', 'Pre-Approved by the Manager'), ('Dispute', 'Dispute'), ('Waived', 'Waived')], default='Submitted', max_length=50, null=True),
        ),
    ]
