# Generated by Django 2.1.2 on 2019-08-14 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190803_1716'),
        ('clienttimesheet', '0014_auto_20190813_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='assigned_pm',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='assigned_va',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='assigned_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Staffs', verbose_name='Assigned VA'),
        ),
    ]
