# Generated by Django 2.1.2 on 2019-08-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienttimesheet', '0016_auto_20190814_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmade',
            options={'ordering': ['-date'], 'verbose_name': "Client's Credit Purchase", 'verbose_name_plural': "Client's Credit Purchases"},
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='admin_approval',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('For Review', 'For Review'), ('Declined', 'Declined'), ('Dispute', 'Dispute'), ('Waived', 'Waived')], default='For Review', max_length=50, null=True),
        ),
    ]
