# Generated by Django 2.2.13 on 2020-07-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienttimesheet', '0017_auto_20190816_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='client_full_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
