# Generated by Django 2.1.2 on 2019-03-14 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fillables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalLandInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closest_major_city', models.CharField(blank=True, max_length=250, null=True)),
                ('closest_small_town', models.CharField(blank=True, max_length=250, null=True)),
                ('nearby_attractions', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessor_website', models.URLField(blank=True, max_length=250, null=True)),
                ('treasurer_website', models.URLField(blank=True, max_length=250, null=True)),
                ('recorder_cleark_website', models.URLField(blank=True, max_length=250, null=True)),
                ('zoning_department_website', models.URLField(blank=True, max_length=250, null=True)),
                ('gis_website', models.URLField(blank=True, max_length=250, null=True)),
                ('cad_website', models.URLField(blank=True, max_length=250, null=True)),
                ('planning_department_contact', models.CharField(blank=True, max_length=250, null=True)),
                ('recorder_clerk_contact', models.CharField(blank=True, max_length=250, null=True)),
                ('tax_office_contact', models.CharField(blank=True, max_length=250, null=True)),
                ('assessors_office_contact', models.CharField(blank=True, max_length=250, null=True, verbose_name="Assessor's Office Contact")),
            ],
        ),
        migrations.CreateModel(
            name='DataOnUtilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.BooleanField(verbose_name='Water?')),
                ('sewer_or_septice', models.CharField(blank=True, choices=[('Sewer', 'Sewer'), ('Septic', 'Septic')], max_length=100, null=True)),
                ('power', models.BooleanField(verbose_name='Power(electricity)?')),
                ('gas', models.BooleanField(verbose_name='Gas?')),
                ('waste', models.BooleanField(verbose_name='Waste?')),
            ],
        ),
        migrations.CreateModel(
            name='DueDiligence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date_requested', models.DateField(blank=True, null=True)),
                ('company_owner', models.CharField(blank=True, max_length=250, null=True)),
                ('date_completed_or_returned', models.DateField(blank=True, null=True, verbose_name='Date Completed or Returned to the Client')),
                ('customer_care_specialist', models.CharField(blank=True, max_length=250, null=True)),
                ('company_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.CompanyName')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_number', models.CharField(blank=True, max_length=250, null=True)),
                ('account_number', models.CharField(blank=True, max_length=259, null=True)),
                ('property_address', models.TextField(blank=True, null=True)),
                ('county', models.CharField(blank=True, max_length=250, null=True)),
                ('lot_number', models.CharField(blank=True, max_length=250, null=True)),
                ('legal_description', models.TextField(blank=True, null=True)),
                ('parcel_size', models.CharField(blank=True, max_length=250, null=True)),
                ('gps_coordinates', models.CharField(blank=True, max_length=250, null=True)),
                ('gps_coordinates_4_corners', models.CharField(blank=True, max_length=250, null=True)),
                ('google_map_link', models.URLField(blank=True, max_length=250, null=True)),
                ('elevation', models.CharField(blank=True, max_length=250, null=True)),
                ('assessed_value', models.CharField(blank=True, max_length=250, null=True)),
                ('access_to_property', models.CharField(blank=True, max_length=250, null=True, verbose_name='Access to Property (Dirt or Paved)')),
                ('owner_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='landmaster.DueDiligence')),
            ],
        ),
        migrations.CreateModel(
            name='TaxData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back_taxes', models.CharField(blank=True, max_length=250, null=True, verbose_name='Back Taxes owed? If so, amount owed.')),
                ('tax_liens', models.CharField(blank=True, max_length=250, null=True, verbose_name='Tax Liens? If so, amount owed.')),
                ('annual_property_taxes', models.CharField(blank=True, max_length=250, null=True)),
                ('is_property_part_of_an_hoa', models.BooleanField()),
                ('how_much_dues', models.CharField(blank=True, max_length=250, null=True, verbose_name='Is so how much are the dues?')),
                ('client_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='landmaster.DueDiligence')),
            ],
        ),
        migrations.CreateModel(
            name='ZoningData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoning', models.CharField(blank=True, max_length=250, null=True)),
                ('terrian_type', models.CharField(blank=True, max_length=250, null=True)),
                ('property_use_code', models.CharField(blank=True, max_length=250, null=True)),
                ('what_can_be_built', models.TextField(blank=True, null=True, verbose_name='What can be build on the property?')),
                ('time_limit_to_build', models.CharField(blank=True, max_length=250, null=True)),
                ('can_camp', models.BooleanField(blank=True, max_length=250, null=True, verbose_name='Can you camp on the property?')),
                ('notes_on_camping', models.TextField(blank=True, null=True)),
                ('rv_allowed', models.BooleanField(verbose_name="RV's allowed on the property?")),
                ('note_on_rv', models.TextField(verbose_name="Note's on RV's")),
                ('mobile_homes', models.BooleanField(verbose_name='Mobile homes allowed on property?')),
                ('notes_on_mobile_homes', models.TextField(blank=True, null=True)),
                ('is_property_flood_zone_area', models.BooleanField(verbose_name='Is the property in the flood zone area?')),
                ('client_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='landmaster.DueDiligence')),
            ],
        ),
        migrations.AddField(
            model_name='dataonutilities',
            name='client_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='landmaster.DueDiligence'),
        ),
        migrations.AddField(
            model_name='countydata',
            name='client_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='landmaster.DueDiligence'),
        ),
        migrations.AddField(
            model_name='additionallandinfo',
            name='client_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='landmaster.DueDiligence'),
        ),
    ]
