# Generated by Django 2.1.2 on 2019-05-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='duediligence',
            name='total_duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
