# Generated by Django 2.1.2 on 2019-03-15 12:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('landmaster', '0002_auto_20190314_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataonutilities',
            options={'verbose_name': 'Data On Utility', 'verbose_name_plural': 'Data On Utilities'},
        ),
        migrations.AlterModelOptions(
            name='duediligence',
            options={'ordering': ['date_requested']},
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
