# Generated by Django 2.1.2 on 2019-05-20 01:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landmaster', '0002_duediligence_total_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duediligence',
            name='customer_care_specialist',
        ),
        migrations.RemoveField(
            model_name='duediligence',
            name='date_completed_initial_dd_time_in',
        ),
        migrations.RemoveField(
            model_name='duediligence',
            name='date_completed_initial_dd_time_out',
        ),
        migrations.RemoveField(
            model_name='duediligence',
            name='date_completed_initial_dd_total_time',
        ),
        migrations.RemoveField(
            model_name='duediligence',
            name='date_completed_other_requests_time_in',
        ),
        migrations.RemoveField(
            model_name='duediligence',
            name='date_completed_other_requests_time_out',
        ),
        migrations.RemoveField(
            model_name='duediligence',
            name='date_completed_other_requests_total_time',
        ),
        migrations.RemoveField(
            model_name='duediligence',
            name='date_completed_tax_data_time_in',
        ),
        migrations.RemoveField(
            model_name='duediligence',
            name='date_completed_tax_data_time_out',
        ),
        migrations.RemoveField(
            model_name='duediligence',
            name='date_completed_tax_data_total_time',
        ),
        migrations.RemoveField(
            model_name='duediligence',
            name='date_completed_utilities_time_in',
        ),
        migrations.RemoveField(
            model_name='duediligence',
            name='date_completed_utilities_time_out',
        ),
        migrations.RemoveField(
            model_name='duediligence',
            name='date_completed_utilities_total_time',
        ),
        migrations.RemoveField(
            model_name='duediligence',
            name='date_completed_zoning_data_time_in',
        ),
        migrations.RemoveField(
            model_name='duediligence',
            name='date_completed_zoning_data_time_out',
        ),
        migrations.RemoveField(
            model_name='duediligence',
            name='date_completed_zoning_data_total_time',
        ),
        migrations.RemoveField(
            model_name='duediligence',
            name='notes_on_deeds',
        ),
        migrations.RemoveField(
            model_name='duediligence',
            name='notes_on_legal_description',
        ),
        migrations.RemoveField(
            model_name='duediligence',
            name='total_duration',
        ),
        migrations.AddField(
            model_name='duediligence',
            name='county_operator_details',
            field=models.CharField(blank=True, help_text="County Operator's Details", max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='electricity_company_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='initial_due_diligence_completion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='natural_gas_company_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='propane_gas_company_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='tax_data_completion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='utilities_data_completion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='utility_department_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='water_company_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='zoning_data_completion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='access_to_property',
            field=models.CharField(blank=True, help_text='Dirt / Paved or No Access', max_length=250, null=True, verbose_name='Access to Property'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='annual_property_taxes',
            field=models.CharField(blank=True, help_text='What is the Annual Property Tax?', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='back_taxes',
            field=models.CharField(blank=True, help_text='Is there any back Taxes owed in the property? If yes, how much is the amount owed...', max_length=250, null=True, verbose_name='Back Taxes owed?'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='cad_website',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='CAD Website'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='can_camp',
            field=models.CharField(blank=True, help_text='If we buy this property can the owner camp there?', max_length=250, null=True, verbose_name='Can you camp on the property?'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='dd_va_assigned_call_outs_other_requests',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='other', to='fillables.VirtualAssistant', verbose_name='VA - Other Requests'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='dd_va_assigned_call_outs_tax_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax', to='fillables.VirtualAssistant', verbose_name='VA - Tax Data'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='dd_va_assigned_call_outs_utilities_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utilities', to='fillables.VirtualAssistant', verbose_name='VA - Utilities Data'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='dd_va_assigned_call_outs_zoning_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zoning', to='fillables.VirtualAssistant', verbose_name='VA - Zoning Data'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='dd_va_assigned_initial_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initial', to='fillables.VirtualAssistant', verbose_name='VA - Initial Data'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='gis_website',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='GIS Website'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='gps_coordinates',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='GPS Coordinates'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='gps_coordinates_4_corners',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='GPS Coordinates 4 Corners'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='how_much_dues',
            field=models.CharField(blank=True, help_text='If yes, how much being the dues?', max_length=250, null=True, verbose_name='how much are the dues?'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='is_property_flood_zone_area',
            field=models.CharField(blank=True, help_text='Is the property in a flood zone area?', max_length=250, null=True, verbose_name='Flood zone area?'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='is_property_part_of_an_hoa',
            field=models.CharField(blank=True, help_text='Is the property part of an HOA?', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='mobile_homes',
            field=models.CharField(blank=True, help_text='Are mobile homes allowed on the property? Please ask if there is restrictions.', max_length=250, null=True, verbose_name='Mobile homes allowed on property?'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='nearby_attractions',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nearby Attractions and Amenities'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='notes_from_the_client',
            field=models.TextField(blank=True, null=True, verbose_name='Client instructions'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='notes_from_the_quality_specialist',
            field=models.TextField(blank=True, null=True, verbose_name='Quality Specialists Evaluation'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='notes_from_the_virtual_assistant',
            field=models.TextField(blank=True, null=True, verbose_name='VA Notes'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='notes_on_camping',
            field=models.TextField(blank=True, help_text='Notes on Camping?', null=True),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='notes_on_mobile_homes',
            field=models.TextField(blank=True, help_text='Notes on mobile homes?', null=True),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='notes_on_tax',
            field=models.TextField(blank=True, null=True, verbose_name='Tax Memo'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='notes_on_utilities',
            field=models.TextField(blank=True, null=True, verbose_name='Utilities Memo'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='notes_on_zoning',
            field=models.TextField(blank=True, null=True, verbose_name='Zoning Memo'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='rv_allowed',
            field=models.CharField(blank=True, help_text="Is RV's allowed on the property? Please ask if there are restrictions.", max_length=250, null=True, verbose_name="RV's allowed on the property?"),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='status_of_dd',
            field=models.CharField(blank=True, choices=[('Sent to Project Manager', 'Sent to Project Manager'), ('Project Managers Review', 'Project Managers Review'), ('Sent to VA', 'Sent to VA'), ('VA Processing', 'VA Processing'), ('Sent to Quality Specialist', 'Sent to Quality Specialist'), ('Quality Specialist Checking', 'Quality Specialist Checking'), ('Submitted to the Client', 'Submitted to the Client'), ('Approved by the Client', 'Approved by the Client')], max_length=150, null=True, verbose_name='Due Diligence Status'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='tax_liens',
            field=models.CharField(blank=True, help_text='Is there any Tax Liens? If yes, how much is the amount owed...', max_length=250, null=True, verbose_name='Tax Liens?'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='terrian_type',
            field=models.CharField(blank=True, help_text='Is it flat or slope? etc.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='time_limit_to_build',
            field=models.CharField(blank=True, help_text='Is there any time limit to build?', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='what_can_be_built',
            field=models.TextField(blank=True, help_text='What can be built on the property? Indicate different types of homes that we can build on the lots.', null=True, verbose_name='What can be build on the property?'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='zoning',
            field=models.CharField(blank=True, help_text='What is the zoning of the property?', max_length=250, null=True),
        ),
    ]
