# Generated by Django 2.1.2 on 2019-03-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmaster', '0003_auto_20190315_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionallandinfo',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='countydata',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='dataonutilities',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='landdata',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='taxdata',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='zoningdata',
            name='client_name',
        ),
        migrations.AlterModelOptions(
            name='duediligence',
            options={'ordering': ('date_requested',)},
        ),
        migrations.AddField(
            model_name='duediligence',
            name='access_to_property',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Access to Property (Dirt or Paved)'),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='account_number',
            field=models.CharField(blank=True, max_length=259, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='annual_property_taxes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='assessed_value',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='assessor_website',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='assessors_office_contact',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="Assessor's Office Contact"),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='back_taxes',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Back Taxes owed? If so, amount owed.'),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='cad_website',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='can_camp',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Can you camp on the property?'),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='closest_major_city',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='closest_small_town',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='county',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='elevation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='gas',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Gas?'),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='gis_website',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='google_map_link',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='gps_coordinates',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='gps_coordinates_4_corners',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='how_much_dues',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Is so how much are the dues?'),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='is_property_flood_zone_area',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Is the property in the flood zone area?'),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='is_property_part_of_an_hoa',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='legal_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='lot_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='mobile_homes',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Mobile homes allowed on property?'),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='nearby_attractions',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='note_on_rv',
            field=models.TextField(blank=True, null=True, verbose_name="Note's on RV's"),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='notes_on_camping',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='notes_on_mobile_homes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='parcel_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='parcel_size',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='planning_department_contact',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='power',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Power(electricity)?'),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='property_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='property_use_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='recorder_cleark_website',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='recorder_clerk_contact',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='rv_allowed',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="RV's allowed on the property?"),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='sewer_or_septice',
            field=models.CharField(blank=True, choices=[('Sewer', 'Sewer'), ('Septic', 'Septic')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='tax_liens',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Tax Liens? If so, amount owed.'),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='tax_office_contact',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='terrian_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='time_limit_to_build',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='treasurer_website',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='waste',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Waste?'),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='water',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Water?'),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='what_can_be_built',
            field=models.TextField(blank=True, null=True, verbose_name='What can be build on the property?'),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='zoning',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='zoning_department_website',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='AdditionalLandInfo',
        ),
        migrations.DeleteModel(
            name='CountyData',
        ),
        migrations.DeleteModel(
            name='DataOnUtilities',
        ),
        migrations.DeleteModel(
            name='LandData',
        ),
        migrations.DeleteModel(
            name='TaxData',
        ),
        migrations.DeleteModel(
            name='ZoningData',
        ),
    ]
