# Generated by Django 2.1.2 on 2019-07-23 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmaster', '0004_updated_dd_cleared_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duediligencescleared',
            options={'ordering': ['-date_of_call'], 'verbose_name': 'Due Diligence Call Out Report', 'verbose_name_plural': 'Due Diligence Call Out Reports'},
        ),
    ]
