# Generated by Django 2.1.2 on 2019-03-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmaster', '0004_unified_all_models_in_due_diligence'),
    ]

    operations = [
        migrations.AddField(
            model_name='duediligence',
            name='owner_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="Owner's name"),
        ),
    ]
