# Generated by Django 2.1.2 on 2019-05-21 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmaster', '0004_auto_20190521_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duediligence',
            name='county_operator_details',
        ),
        migrations.RemoveField(
            model_name='duediligence',
            name='date_completed',
        ),
        migrations.RemoveField(
            model_name='duediligence',
            name='status_of_dd',
        ),
    ]
