# Generated by Django 2.1.2 on 2019-03-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmaster', '0005_added_owners_name_in_due_diligence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duediligence',
            name='recorder_cleark_website',
        ),
        migrations.AddField(
            model_name='duediligence',
            name='recorder_clerk_website',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Recorder/Clerk Website'),
        ),
    ]
