# Generated by Django 2.1.2 on 2019-07-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmaster', '0005_auto_20190723_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='duediligence',
            name='additional_client_request_memo',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Client Request Memo from Cust. Rep'),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='additional_client_request_question',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Client Request Question/s'),
        ),
    ]
