# Generated by Django 2.1.2 on 2019-05-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmaster', '0006_duediligence_status_of_dd'),
    ]

    operations = [
        migrations.AddField(
            model_name='duediligence',
            name='level_of_urgency',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Average', 'Average'), ('Low', 'Low')], max_length=150, null=True),
        ),
    ]
