# Generated by Django 2.1.2 on 2019-03-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmaster', '0007_auto_20190318_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duediligence',
            name='company_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
