# Generated by Django 2.1.2 on 2019-07-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmaster', '0007_auto_20190724_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duediligence',
            name='assessor_website',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='attachments',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='cad_website',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='CAD Website'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='gis_website',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='GIS Website'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='google_map_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='recorder_clerk_website',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Recorder/Clerk Website'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='treasurer_website',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='zoning_department_website',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
