# Generated by Django 2.1.2 on 2019-05-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmaster', '0007_duediligence_level_of_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duediligence',
            name='other_requests_completion',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Completion – Other Requests'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='tax_data_completion',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Completion – Tax Data'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='utilities_data_completion',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Completion – Utilities Data'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='zoning_data_completion',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Completion – Zoning Data'),
        ),
    ]
