# Generated by Django 2.1.2 on 2019-03-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmaster', '0008_auto_20190318_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duediligence',
            old_name='sewer_or_septice',
            new_name='sewer_or_septic',
        ),
    ]
