# Generated by Django 2.1.2 on 2019-08-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmaster', '0009_auto_20190815_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duediligence',
            name='assessors_office_contact',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="Assessor's Office Contact"),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='tax_office_contact',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
