# Generated by Django 2.1.2 on 2019-05-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmaster', '0009_auto_20190521_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='duediligence',
            name='county_operator_details',
            field=models.CharField(blank=True, help_text="County Operator's Details", max_length=250, null=True),
        ),
    ]
