# Generated by Django 2.1.2 on 2019-03-27 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fillables', '0002_added_va'),
        ('landmaster', '0009_auto_20190320_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='duediligence',
            name='dd_team_assigned_va',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.VirtualAssistant', verbose_name='DD Team Assigned VA'),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.ProjectManager'),
        ),
    ]
