# Generated by Django 2.1.2 on 2019-03-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmaster', '0010_additional_on_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='duediligence',
            name='total_minutes_hours_duration',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Total Minutes/hours duration'),
        ),
    ]
