# Generated by Django 2.1.2 on 2019-05-30 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmaster', '0010_duediligence_county_operator_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duediligencescleared',
            options={'ordering': ['-date_of_call'], 'verbose_name': 'Due Diligence Call Tracking Report', 'verbose_name_plural': 'Due Diligence Call Tracking Reports'},
        ),
    ]
