# Generated by Django 2.1.2 on 2019-08-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmaster', '0011_auto_20190816_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duediligence',
            name='nearby_attractions',
            field=models.TextField(blank=True, null=True, verbose_name='Nearby Attractions and Amenities'),
        ),
    ]
