# Generated by Django 2.1.2 on 2019-06-10 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landmaster', '0011_auto_20190530_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duediligence',
            name='dd_va_assigned_call_outs_other_requests',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='other', to='users.Staffs', verbose_name='VA - Other Requests'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='dd_va_assigned_call_outs_tax_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax', to='users.Staffs', verbose_name='VA - Tax Data'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='dd_va_assigned_call_outs_utilities_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utilities', to='users.Staffs', verbose_name='VA - Utilities Data'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='dd_va_assigned_call_outs_zoning_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zoning', to='users.Staffs', verbose_name='VA - Zoning Data'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='dd_va_assigned_initial_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initial', to='users.Staffs', verbose_name='VA - Initial Data'),
        ),
    ]
