# Generated by Django 2.1.2 on 2019-04-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmaster', '0012_added_attachments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duediligence',
            old_name='company_owner',
            new_name='company_owner_or_requestor',
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='customer_care_specialist',
            field=models.CharField(blank=True, help_text='Customer Care Specialist or Operator ID  Assessors/County', max_length=250, null=True),
        ),
    ]
