# Generated by Django 2.1.2 on 2019-06-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmaster', '0012_changed_the_vas_to_auth_staffs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duediligence',
            name='status_initial_data',
            field=models.CharField(blank=True, choices=[('Sent to Project Manager', 'Sent to Project Manager'), ('Project Managers Review', 'Project Managers Review'), ('Sent to VA', 'Sent to VA'), ('VA Processing', 'VA Processing'), ('Sent to Quality Specialist', 'Sent to Quality Specialist'), ('Quality Specialist Checking', 'Quality Specialist Checking'), ('Submitted to the Client', 'Submitted to the Client'), ('Approved by the Client', 'Approved by the Client')], max_length=150, null=True, verbose_name='Due Diligence Status for Initial Data'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='status_other_requests',
            field=models.CharField(blank=True, choices=[('Sent to Project Manager', 'Sent to Project Manager'), ('Project Managers Review', 'Project Managers Review'), ('Sent to VA', 'Sent to VA'), ('VA Processing', 'VA Processing'), ('Sent to Quality Specialist', 'Sent to Quality Specialist'), ('Quality Specialist Checking', 'Quality Specialist Checking'), ('Submitted to the Client', 'Submitted to the Client'), ('Approved by the Client', 'Approved by the Client')], max_length=150, null=True, verbose_name='Due Diligence Status for Other Requests'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='status_tax_data',
            field=models.CharField(blank=True, choices=[('Sent to Project Manager', 'Sent to Project Manager'), ('Project Managers Review', 'Project Managers Review'), ('Sent to VA', 'Sent to VA'), ('VA Processing', 'VA Processing'), ('Sent to Quality Specialist', 'Sent to Quality Specialist'), ('Quality Specialist Checking', 'Quality Specialist Checking'), ('Submitted to the Client', 'Submitted to the Client'), ('Approved by the Client', 'Approved by the Client')], max_length=150, null=True, verbose_name='Due Diligence Status for Tax Data'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='status_utilities_data',
            field=models.CharField(blank=True, choices=[('Sent to Project Manager', 'Sent to Project Manager'), ('Project Managers Review', 'Project Managers Review'), ('Sent to VA', 'Sent to VA'), ('VA Processing', 'VA Processing'), ('Sent to Quality Specialist', 'Sent to Quality Specialist'), ('Quality Specialist Checking', 'Quality Specialist Checking'), ('Submitted to the Client', 'Submitted to the Client'), ('Approved by the Client', 'Approved by the Client')], max_length=150, null=True, verbose_name='Due Diligence Status for Utilities Data'),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='status_zoning_data',
            field=models.CharField(blank=True, choices=[('Sent to Project Manager', 'Sent to Project Manager'), ('Project Managers Review', 'Project Managers Review'), ('Sent to VA', 'Sent to VA'), ('VA Processing', 'VA Processing'), ('Sent to Quality Specialist', 'Sent to Quality Specialist'), ('Quality Specialist Checking', 'Quality Specialist Checking'), ('Submitted to the Client', 'Submitted to the Client'), ('Approved by the Client', 'Approved by the Client')], max_length=150, null=True, verbose_name='Due Diligence Status for Zoning Data'),
        ),
    ]
