# Generated by Django 2.1.2 on 2019-04-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmaster', '0013_auto_20190420_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duediligence',
            old_name='notes_from_land_master_team',
            new_name='notes_from_the_quality_specialist',
        ),
        migrations.AddField(
            model_name='duediligence',
            name='notes_from_the_virtual_assistant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='status_of_dd',
            field=models.CharField(blank=True, choices=[('Project Managers Review', 'Project Managers Review'), ('Submitted to the Client', 'Submitted to the Client'), ('Approved by the Client', 'Approved by the Client')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='duediligence',
            name='customer_care_specialist',
            field=models.CharField(blank=True, help_text='Customer Care Specialist or Operator ID, Assessors/County', max_length=250, null=True),
        ),
    ]
