# Generated by Django 2.1.4 on 2019-04-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmaster', '0016_auto_20190421_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duediligence',
            name='status_of_dd',
            field=models.CharField(blank=True, choices=[('Sent to Project Manager', 'Sent to Project Manager'), ('Project Managers Review', 'Project Managers Review'), ('Sent to VA', 'Sent to VA'), ('VA Processing', 'VA Processing'), ('Sent to Quality Specialist', 'Sent to Quality Specialist'), ('Quality Specialist Checking', 'Quality Specialist Checking'), ('Submitted to the Client', 'Submitted to the Client'), ('Approved by the Client', 'Approved by the Client')], max_length=150, null=True),
        ),
    ]
