# Generated by Django 2.1.2 on 2019-05-04 05:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fillables', '0002_added_va'),
        ('landmaster', '0017_auto_20190421_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='DueDiligencesCleared',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_call', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('client_full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('client_company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('apn', models.CharField(blank=True, max_length=150, null=True)),
                ('call_in', models.DateTimeField(blank=True, null=True)),
                ('call_out', models.DateTimeField(blank=True, null=True)),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('department_calling_about', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=150, null=True)),
                ('operators_details', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer_service_representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.VirtualAssistant')),
            ],
            options={
                'verbose_name': 'Due Diligences Cleared Information',
                'verbose_name_plural': 'Due Diligences Cleared Informations',
                'ordering': ['-date_of_call'],
            },
        ),
    ]
