# Generated by Django 2.1.2 on 2019-05-04 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landmaster', '0018_duediligencescleared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duediligencescleared',
            name='call_in',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='duediligencescleared',
            name='call_out',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
