# Generated by Django 2.1.2 on 2019-05-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmaster', '0019_auto_20190504_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duediligencescleared',
            name='customer_service_representative',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
