# Generated by Django 2.1.2 on 2019-05-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmaster', '0020_auto_20190504_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='duediligence',
            name='notes_on_deeds',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='notes_on_legal_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='notes_on_tax',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='notes_on_utilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='notes_on_zoning',
            field=models.TextField(blank=True, null=True),
        ),
    ]
