# Generated by Django 2.1.2 on 2019-05-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmaster', '0023_auto_20190507_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duediligence',
            name='status_of_dd',
            field=models.CharField(blank=True, choices=[('SENT-TO-THE-PROJECT-MANAGER', 'Sent to Project Manager'), ('PROJECT-MANAGERS-REVIEW', 'Project Managers Review'), ('SENT-TO-VA', 'Sent to VA'), ('VA-PROCESSING', 'VA Processing'), ('SENT-TO-QUALITY-SPECIALIST', 'Sent to Quality Specialist'), ('QUALITY-SPECIALIST-CHECKING', 'Quality Specialist Checking'), ('SUBMITTED-TO-THE-CLIENT', 'Submitted to the Client'), ('APPROVED-BY-THE-CLIENT', 'Approved by the Client')], max_length=150, null=True),
        ),
    ]
