# Generated by Django 2.1.2 on 2019-04-05 09:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fillables', '0002_added_va'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logins',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('type_of_apps', models.CharField(blank=True, max_length=150, null=True)),
                ('link_to_the_app', models.URLField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=150, null=True)),
                ('password', models.CharField(blank=True, max_length=150, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('give_access_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.VirtualAssistant')),
            ],
            options={
                'verbose_name': 'List of Logins of the client',
                'verbose_name_plural': 'List of Logins of the clients',
                'ordering': ['client_full_name'],
            },
        ),
    ]
