# Generated by Django 2.1.2 on 2019-06-11 14:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logins',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('company_category', models.CharField(blank=True, choices=[('landmaster.us', 'landmaster.us'), ('gpgcorporations.com', 'gpgcorporations.com'), ('callme.com.ph', 'callme.com.ph'), ('virtualExpressServices.com', 'virtualExpressServices.com'), ('creatif-designs.com', 'creatif-designs.com'), ('vacantpropertiesglobal.com', 'vacantpropertiesglobal.com')], max_length=150, null=True)),
                ('apps_url_link', models.URLField(blank=True, null=True)),
                ('type_of_apps', models.CharField(blank=True, max_length=150, null=True)),
                ('link_to_the_app', models.URLField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=150, null=True)),
                ('password', models.CharField(blank=True, max_length=150, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('added_by', models.CharField(blank=True, max_length=150, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'General Login',
                'verbose_name_plural': 'General Logins',
                'ordering': ['client_full_name'],
            },
        ),
    ]
