# Generated by Django 2.1.2 on 2019-06-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logins',
            name='apps_url_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
