# Generated by Django 2.1.2 on 2019-05-02 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logins',
            name='added_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='logins',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logins',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
