# Generated by Django 2.1.2 on 2019-06-11 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('logins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logins',
            name='client_full_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Clients'),
        ),
        migrations.AddField(
            model_name='logins',
            name='give_access_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Staffs'),
        ),
    ]
