# Generated by Django 2.1.2 on 2019-08-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190803_1716'),
        ('logins', '0002_auto_20190611_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logins',
            name='give_access_to',
        ),
        migrations.AddField(
            model_name='logins',
            name='give_access_to',
            field=models.ManyToManyField(related_name='accesses', to='users.Staffs'),
        ),
    ]
