# Generated by Django 2.1.2 on 2019-06-11 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0002_logins_apps_url_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logins',
            name='date_added',
        ),
    ]
