# Generated by Django 2.1.2 on 2019-06-11 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0003_remove_logins_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logins',
            name='give_access_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillables.VirtualAssistant'),
        ),
    ]
