# Generated by Django 2.1.2 on 2019-08-16 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190803_1716'),
        ('logins', '0003_manytomany in give access to in logins app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logins',
            name='give_access_to',
        ),
        migrations.AddField(
            model_name='logins',
            name='give_access_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Staffs'),
        ),
    ]
