# Generated by Django 2.1.2 on 2018-10-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='job_request_title',
            field=models.CharField(default='Give me a title later', max_length=250),
        ),
    ]
